import type { Question, Step } from './chapter';

export const chatSteps: Step[] = [
  {
    id: 'chat-scope', title: 'Define the conversation', eyebrow: '01 · Product boundary',
    summary: 'Decide whose messages move where before selecting a transport or database.',
    body: [
      '“Build chat” leaves important choices unanswered. For this design, assume text messages, one-to-one conversations, groups of at most 100 members, multiple devices per account, online indicators, and notifications when the app is away. Agree on a target audience, latency goal, history retention, and whether edits, attachments, or end-to-end encryption belong in the first release.',
      'Separate sending a message from receiving it. A sender needs an acceptance result; an online recipient should see the message quickly; an offline recipient should find it on return. These are three different promises. A green dot or push notification cannot stand in for durable message delivery.',
      'Estimate active concurrent connections, messages per second at peak, average message size, and group fanout. Registered accounts alone cannot size a connection fleet. Carry uncertain numbers as assumptions and revisit them when the path is designed.',
    ],
    takeaways: ['State the exact chat product and first-release boundary.', 'Define acceptance, live delivery, and later retrieval as separate outcomes.'],
    diagramId: 'chat-scope',
    scenario: 'A team asks for “real-time chat” and says nothing about groups, devices, or offline users. What should the first design conversation establish?',
    scenarioAnswer: 'Ask which conversation types matter, whether one account has several devices, what happens offline, how long history is kept, and what latency or load is expected. Record assumptions before choosing WebSocket or a store.',
  },
  {
    id: 'chat-transport', title: 'Choose the live transport', eyebrow: '02 · Client and server',
    summary: 'Compare polling, long polling, and WebSocket against update frequency and connection cost.',
    body: [
      'Ordinary HTTP works well for login and profile changes and can also send a message. For live delivery, short polling repeatedly asks for updates, creating empty requests when traffic is quiet. Long polling waits for an event or timeout before the client opens another request; it reduces empty replies but still needs reconnect and timeout handling.',
      'A WebSocket starts with a client handshake and then holds a bidirectional channel. It suits frequent asynchronous chat updates, but the server must manage many live connections, heartbeats, reconnects, backpressure, and authentication refresh. A persistent channel is a delivery path, not durable storage.',
      'Use the simplest transport that meets the product’s latency and scale goals. This chapter uses WebSocket for live send and receive while keeping routine account APIs on HTTP. Mobile push wakes an inactive device; it is a notification path and may be delayed or disabled.',
    ],
    takeaways: ['Polling trades simplicity for repeated requests; long polling holds requests; WebSocket keeps a bidirectional channel.', 'Choose transport separately from persistence and push notification.'],
    diagramId: 'chat-transport',
    scenario: 'A support inbox gets one update every few hours, while a game lobby exchanges updates each second. Would both need WebSocket?',
    scenarioAnswer: 'Probably not. A quiet inbox can begin with polling or long polling if latency targets permit. Frequent lobby updates favor a persistent bidirectional connection. Measure connection and request cost for the actual workload.',
  },
  {
    id: 'chat-connections', title: 'Place and recover connections', eyebrow: '03 · Connection lifecycle',
    summary: 'Route each device to a healthy gateway and track where its live channel resides.',
    body: [
      'After authentication, a placement service chooses a healthy chat gateway with capacity near the device. The device connects and registers its user and device identity. A routing directory maps the active device to its gateway; the gateway owns the socket while connected.',
      'One account may have a phone and laptop on different gateways. Do not assume “user online” means there is only one destination. Gateways need limits for connection count, memory, and outbound queues. Drain them during deployment so clients reconnect gradually rather than all at once.',
      'If a gateway fails, the socket disappears. The client reconnects, authenticates again, receives a new placement, and requests messages since its last acknowledged cursor. The routing directory is a hint to live delivery; stored history is the recovery source.',
    ],
    takeaways: ['Track live routes per device, not only per account.', 'Reconnect plus catch-up repairs a broken channel; a load balancer alone cannot recover messages.'],
    diagramId: 'chat-connections',
    scenario: 'A gateway holding 80,000 sockets restarts. What must happen before clients can safely resume?',
    scenarioAnswer: 'Clients reconnect to healthy gateways with capacity, authenticate, re-register their routes, and fetch any messages beyond their saved cursors. Use gradual retries and gateway draining to avoid a reconnect storm.',
  },
  {
    id: 'chat-delivery', title: 'Follow one message end to end', eyebrow: '04 · One-to-one flow',
    summary: 'Persist a message once, then try live delivery or notify an offline recipient.',
    body: [
      'The sender submits a client-generated idempotency key with the conversation ID and text. The chat service validates membership, assigns a server message ID and position, persists the record, and acknowledges acceptance. Only then should the sender show a durable “sent” state. A retry with the same key must not create a second message.',
      'The delivery worker checks each recipient device’s live route. It pushes to connected devices and may ask the notification service to wake inactive ones. Push notifications are hints; clients retrieve history from storage to fill gaps. If the receiver is offline, the durable message remains available.',
      'Distinguish accepted, delivered to a device, and read by a person. These acknowledgements may arrive later or never. A network timeout after persistence is ambiguous to the sender, which is why idempotency and client-side reconciliation matter.',
    ],
    takeaways: ['Persist before claiming durable acceptance.', 'Retries and offline catch-up need stable IDs and idempotency; push is not the source of truth.'],
    diagramId: 'chat-delivery',
    scenario: 'The server saves a message but its acknowledgement is lost. The sender retries. What should the service return?',
    scenarioAnswer: 'Look up the original idempotency key and return the existing message ID and status. A new row would duplicate the message. The receiver can still retrieve the persisted record even if the sender never saw the first acknowledgement.',
  },
  {
    id: 'chat-ordering', title: 'Order and sync the history', eyebrow: '05 · Conversation timeline',
    summary: 'Give each conversation a stable sequence and each device a recovery cursor.',
    body: [
      'Client clocks and wall-clock timestamps cannot reliably order concurrent messages. Assign a monotonically increasing position within each conversation (or another sortable server-side order) and use a globally unique message ID for identity. A per-conversation sequence is often enough; the whole product need not share one total order.',
      'Store messages keyed for the read pattern, such as conversation ID plus sequence, and page forward or backward from a cursor. Each device tracks the highest contiguous position it has applied per conversation. On reconnect, fetch positions after that cursor and deduplicate messages already seen through live delivery.',
      'Ordering comes with a coordination cost. If one conversation gets exceptionally hot, its sequencer or partition may become a bottleneck; explain the chosen consistency promise rather than assuming that adding shards gives strict order for free. Membership changes and deletions also need explicit timeline semantics.',
    ],
    takeaways: ['Timestamps alone do not define a dependable conversation order.', 'Cursors are per device and conversation; replay plus deduplication closes live-delivery gaps.'],
    diagramId: 'chat-ordering',
    scenario: 'A phone has seen messages through position 44; a laptop stopped at 39. Both reconnect. What should each request?',
    scenarioAnswer: 'The phone requests positions after 44 and the laptop after 39 for that conversation. Both merge replay with any live arrivals by message ID or sequence, avoiding duplicates and preserving the server-defined order.',
  },
  {
    id: 'chat-presence', title: 'Treat presence as a hint', eyebrow: '06 · Online status',
    summary: 'Use leases and heartbeats so brief network gaps do not make status flicker.',
    body: [
      'A connected device periodically renews a short-lived lease in a presence service. A logout can clear that device immediately; an abrupt disconnect expires after a grace period. An account is online when at least one eligible device has a current lease. Presence is approximate because heartbeats, routing, and observers are never perfectly simultaneous.',
      'Publish meaningful status changes to people currently viewing a small conversation or contact list. Sending every status flip to every member of a huge group can be much more expensive than message traffic. Large audiences can fetch a snapshot when they open the view, then subscribe only while interested.',
      'Do not let presence decide whether to store a message. A recipient can disappear between a status check and a send. Persist first, attempt live delivery, and use the stored record for later catch-up.',
    ],
    takeaways: ['Presence should tolerate transient disconnects and multiple devices.', 'Presence is advisory; durable delivery does not depend on a green dot.'],
    diagramId: 'chat-presence',
    scenario: 'A person’s phone loses signal for eight seconds in a tunnel, but their laptop stays connected. Should the contact list show them offline?',
    scenarioAnswer: 'No. The account still has a live laptop lease. Even without it, a short grace period can avoid a misleading offline/online flicker during a transient phone gap.',
  },
  {
    id: 'chat-groups', title: 'Fan out to a small group', eyebrow: '07 · Shared conversations',
    summary: 'Write one group message, then deliver it to eligible members and devices.',
    body: [
      'Authorize the sender against the group membership version, assign a sequence in that group, and persist one canonical message. A fanout job can put references in recipients’ inboxes or push live events to their devices. For groups capped near 100 members, this write-side work may make each person’s inbox simple to read.',
      'Do not confuse copies in delivery queues with copies of the canonical record. Decide what someone joining later may see, what happens when a member leaves, and whether a retry may repeat a fanout task. Idempotent fanout and membership checks keep those cases predictable.',
      'For a very large channel, copying a message to every follower is costly. Store by channel and let readers pull or use a hybrid for active members. The threshold depends on active readership, group size, and latency goals; “always fan out on write” is not a universal rule.',
    ],
    takeaways: ['Small-group fanout buys simple inbox reads at a bounded write cost.', 'Large audiences may need pull or hybrid delivery, with explicit membership semantics.'],
    diagramId: 'chat-groups',
    scenario: 'A product lifts the group cap from 100 to 100,000. What part of the design deserves immediate review?',
    scenarioAnswer: 'Review per-member fanout and presence broadcasts. A single post or status change could create 100,000 events. Consider canonical channel storage with pull for inactive readers and selective push for active ones.',
  },
  {
    id: 'chat-recovery', title: 'Design the failure path', eyebrow: '08 · Reliability and operations',
    summary: 'Recover from broken sockets and stalled workers without losing or duplicating messages.',
    body: [
      'Separate the durable message log from ephemeral connection state and delivery jobs. Replicate or otherwise protect the log, monitor write latency and lag, and keep a retryable queue for fanout. A worker crash should leave a job available for another worker; at-least-once processing requires idempotent effects.',
      'Watch socket count per gateway, reconnect rate, outbound queue depth, end-to-end delivery delay, replay backlog, failed pushes, and storage errors. Add capacity based on concurrent connections and message fanout rather than daily users alone. Rate limits and backpressure protect gateways from slow clients or abusive senders.',
      'A full end-to-end encryption requirement would change key management, multi-device handling, moderation, and server-side search. Media attachments would add object storage, upload processing, scanning, and CDN delivery. Keep those as explicit next design changes rather than quietly assuming this text-only system already supports them.',
    ],
    takeaways: ['Durable storage, retryable jobs, idempotency, and replay each address a different failure.', 'Measure connections, fanout, lag, and recovery; revisit the design when scope changes.'],
    diagramId: 'chat-recovery',
    scenario: 'A delivery worker crashes after pushing to one device but before acknowledging its job. What happens when the job runs again?',
    scenarioAnswer: 'The job is retried. The device may receive the event again, so it deduplicates by stable message ID. The canonical record remains one message, while at-least-once delivery and idempotent processing make recovery safe.',
  },
];

export const chatQuestions: Question[] = [
  { id:'chat-q01', stepId:'chat-scope', difficulty:'Recall', prompt:'Which requirement most directly changes the live routing model?', options:['The font used in a message bubble','Multiple devices can be connected to one account','The profile screen has a dark theme','The home page has a help link'], correctIndex:1, explanation:'A user can have several active device connections, potentially on different gateways. Delivery must locate and handle each eligible device.' },
  { id:'chat-q02', stepId:'chat-scope', difficulty:'Apply', prompt:'A PM says “a sent message must survive the receiver being offline.” What system promise does that require?', options:['A green online indicator','A shorter polling interval','Durable storage and later catch-up','A push notification only'], correctIndex:2, explanation:'The server must retain the message and let the recipient fetch it later. Presence and push cannot guarantee history.' },
  { id:'chat-q03', stepId:'chat-scope', difficulty:'Diagnose', prompt:'A capacity estimate uses 50 million registered users as 50 million open sockets. What is the missing input?', options:['Concurrent active connections and devices per active user','The number of CSS files','The color of the online dot','The message bubble width'], correctIndex:0, explanation:'Only concurrently connected devices consume sockets. Registered accounts do not reveal that concurrency.' },
  { id:'chat-q04', stepId:'chat-transport', difficulty:'Recall', prompt:'What is the distinctive cost of short polling for a mostly quiet inbox?', options:['It needs a message queue for every request','It cannot use HTTP','It requires one socket per contact','It sends many requests that return no update'], correctIndex:3, explanation:'Periodic checks continue even when there is nothing to deliver, consuming client, network, and server resources.' },
  { id:'chat-q05', stepId:'chat-transport', difficulty:'Apply', prompt:'Which path best fits frequent server-initiated chat updates?', options:['A persistent WebSocket channel with connection management','A CDN object per message','DNS polling on each send','A daily batch job'], correctIndex:0, explanation:'WebSocket offers a bidirectional live channel. The gateway still needs authentication, heartbeats, reconnects, and backpressure.' },
  { id:'chat-q06', stepId:'chat-transport', difficulty:'Diagnose', prompt:'A team selects WebSocket and removes persistent message storage. Why is that unsafe?', options:['WebSocket cannot send text','A socket only reaches connected clients and can fail','Long polling is mandatory','Push notifications write history'], correctIndex:1, explanation:'The live channel carries events but does not retain messages for offline clients or recovery after a disconnect.' },
  { id:'chat-q07', stepId:'chat-connections', difficulty:'Recall', prompt:'What should a live routing directory identify?', options:['Only the most recent login time','The database shard used by every contact','Each active device and the gateway holding its socket','The sender’s local wall clock'], correctIndex:2, explanation:'A single account may have multiple connected devices on different gateways; routing must account for each live destination.' },
  { id:'chat-q08', stepId:'chat-connections', difficulty:'Apply', prompt:'A gateway is being drained for deployment. What reduces disruption?', options:['Move history into gateway memory','Delete routing records before clients know','Disable message persistence','Stop new placements and let existing clients reconnect gradually'], correctIndex:3, explanation:'Capacity-aware placement and gradual reconnection limit storms while clients recover missed messages from storage.' },
  { id:'chat-q09', stepId:'chat-connections', difficulty:'Diagnose', prompt:'After gateway failure, a new socket connects but the client misses ten messages. Which step was omitted?', options:['Catch up from durable history using its saved cursor','Recolor the online indicator','Increase the DNS TTL','Add another profile API'], correctIndex:0, explanation:'Re-establishing a live route does not replay events sent during the gap. Cursor-based retrieval fills it.' },
  { id:'chat-q10', stepId:'chat-delivery', difficulty:'Recall', prompt:'What should “accepted” mean in this design?', options:['A push notification was shown','A stable message record was persisted','Every recipient read the text','The recipient is online'], correctIndex:1, explanation:'Acceptance is a durable server-side result. Live delivery and read receipts are later, separate events.' },
  { id:'chat-q11', stepId:'chat-delivery', difficulty:'Apply', prompt:'The client times out just after the service commits a message. How can a retry avoid duplication?', options:['Trust the client timestamp','Discard all retries','Reuse a client idempotency key and return the original result','Send a second notification'], correctIndex:2, explanation:'A stable key lets the server recognize the same logical submission even when its first acknowledgement was lost.' },
  { id:'chat-q12', stepId:'chat-delivery', difficulty:'Diagnose', prompt:'A mobile push arrives while the app was offline, but the text is absent from history. What is the main fault?', options:['The recipient had too many contacts','WebSocket was bidirectional','The sender used HTTP','Notification was treated as delivery without durable storage'], correctIndex:3, explanation:'Push is a wake-up or alert path. The canonical message must be committed so the app can retrieve it.' },
  { id:'chat-q13', stepId:'chat-ordering', difficulty:'Recall', prompt:'Why are client timestamps inadequate as the only conversation order?', options:['Clocks can differ and concurrent events can share a timestamp','They use too much disk','They cannot be displayed in a UI','They require WebSocket'], correctIndex:0, explanation:'Clock skew and ties make time alone ambiguous. A server-defined per-conversation position gives a clear order.' },
  { id:'chat-q14', stepId:'chat-ordering', difficulty:'Apply', prompt:'A laptop last applied position 28 and then reconnects. What should it request?', options:['All messages ever written by the sender','Positions after 28 for that conversation','Only messages with today’s timestamp','The phone’s cursor'], correctIndex:1, explanation:'A device-specific cursor lets the laptop retrieve just the missing suffix and reconcile it with live messages.' },
  { id:'chat-q15', stepId:'chat-ordering', difficulty:'Diagnose', prompt:'Two shards each assign local sequence 57 to the same conversation. Which assumption failed?', options:['Messages should be encrypted','Groups should use polling','Ordering needs coordination within the conversation','Push should be disabled'], correctIndex:2, explanation:'A strict conversation order needs one coherent sequencer or equivalent coordination. Independent counters cannot define it.' },
  { id:'chat-q16', stepId:'chat-presence', difficulty:'Recall', prompt:'What does a presence lease represent?', options:['A permanent message record','A read receipt','A database backup','A recently renewed signal that a device may be online'], correctIndex:3, explanation:'Heartbeats refresh temporary liveness state. Expiration and grace periods make the indicator approximate rather than an absolute truth.' },
  { id:'chat-q17', stepId:'chat-presence', difficulty:'Apply', prompt:'A phone disconnects briefly but a laptop remains connected. What is the best account-level status?', options:['Online, because at least one device has a current lease','Offline until the phone returns','Always unknown','Use the message sequence as status'], correctIndex:0, explanation:'Account presence aggregates eligible devices. The laptop still provides a current online signal.' },
  { id:'chat-q18', stepId:'chat-presence', difficulty:'Diagnose', prompt:'A celebrity group emits 100,000 presence updates for each status flip. What should change?', options:['Persist each update in chat history','Fetch or selectively subscribe when viewers need status','Increase heartbeat frequency','Use the online dot to decide message persistence'], correctIndex:1, explanation:'Broadcasting presence to every group member grows with audience size. Snapshot-on-view or selective subscriptions can bound work.' },
  { id:'chat-q19', stepId:'chat-groups', difficulty:'Recall', prompt:'Why can per-member inbox fanout be practical for a group capped at 100?', options:['It eliminates the canonical record','It guarantees exactly-once network delivery','Bounded copies simplify each recipient’s read path','It removes the need for membership checks'], correctIndex:2, explanation:'A small cap bounds write-side fanout, while each member can read a personal inbox efficiently. Durable canonical storage and authorization still matter.' },
  { id:'chat-q20', stepId:'chat-groups', difficulty:'Apply', prompt:'The group grows to 100,000 mostly inactive followers. Which approach deserves consideration?', options:['Copy every status and message to every follower','Use only one gateway','Delete old messages immediately','Keep canonical channel history and let inactive readers pull'], correctIndex:3, explanation:'Pull or hybrid delivery avoids 100,000 writes for every event when most members are not reading.' },
  { id:'chat-q21', stepId:'chat-groups', difficulty:'Diagnose', prompt:'A retryable fanout task gives one member two identical inbox entries. What was missing?', options:['Idempotent recipient-side fanout keyed by message and member','A faster CPU on the sender','A longer group name','A profile cache'], correctIndex:0, explanation:'Jobs may run more than once. A unique message-member key or equivalent deduplication prevents duplicate inbox references.' },
  { id:'chat-q22', stepId:'chat-recovery', difficulty:'Recall', prompt:'Which state must survive a gateway restart?', options:['Its local socket objects','The canonical message history','The gateway process heap','An in-memory outbound buffer only'], correctIndex:1, explanation:'Sockets are ephemeral. Durable history is needed to recover missed messages when clients reconnect to another gateway.' },
  { id:'chat-q23', stepId:'chat-recovery', difficulty:'Apply', prompt:'Which metric best exposes growing time between persistence and recipient delivery?', options:['Homepage image count','Total registered accounts','End-to-end delivery lag','Source file count'], correctIndex:2, explanation:'Delivery lag measures the actual user-facing delay and can reveal queue, gateway, or push bottlenecks.' },
  { id:'chat-q24', stepId:'chat-recovery', difficulty:'Diagnose', prompt:'A worker crash causes a fanout job to run twice. What pair keeps the system safe?', options:['Sticky sessions and CDN','Longer DNS TTL and polling','Presence and read receipts','Retryable jobs and idempotent delivery effects'], correctIndex:3, explanation:'The job must remain available after a crash, and repeated execution must not create duplicate canonical messages or inbox entries.' },
];
