import type { Question, Step } from './chapter';

export const frameworkSteps: Step[] = [
  {
    id: 'framework-scope',
    title: 'Turn a broad request into a problem',
    eyebrow: '01 · Establish scope',
    summary: 'Pause before choosing technology and agree on the job the system must do.',
    body: [
      'A request such as “build a news feed” can describe many products. Ask who uses it, which actions matter most, and what the first version must support. A feed of recent friends’ posts has a different shape from one that ranks videos from strangers.',
      'Name the core use cases, identify what can wait, and confirm that boundary with the people making the request. The purpose is to design the right system for a stated problem, not to include every technology you know.',
    ],
    takeaways: ['Clarify users, core actions, and first-release boundaries before drawing infrastructure.', 'Record scope as a decision to revisit when the problem changes.'],
    diagramId: 'framework-scope',
    scenario: 'A teammate says, “We need a social feed.” What would you ask before proposing storage or caching?',
    scenarioAnswer: 'Ask who creates and reads posts, whether the feed contains friends’ posts or recommendations, how it is ordered, which media types it supports, and what must ship first.',
  },
  {
    id: 'framework-requirements',
    title: 'Separate behavior from constraints',
    eyebrow: '02 · Requirements and assumptions',
    summary: 'Write down what the product does, how well it must work, and what remains unknown.',
    body: [
      'Functional requirements describe observable actions: publish a post, view a feed, or attach a photo. Quality requirements describe the conditions under which those actions must work: response time, availability, durability, privacy, and expected load. A feature can work in a demo and still fail in production.',
      'Ask for figures and priorities when they exist. When they do not, make an explicit assumption with a reason and mark it for confirmation. Assuming reverse chronological ordering simplifies a feed, but it is a product choice. Existing services and team constraints also affect the design.',
    ],
    takeaways: ['Functional requirements say what happens; quality requirements say how well and under what load.', 'Make uncertain assumptions visible before they harden into architecture.'],
    diagramId: 'framework-requirements',
    scenario: 'A feed must let people post and read, but nobody specified ordering or traffic. How do you proceed?',
    scenarioAnswer: 'Record posting and reading as features. Ask for ordering and usage expectations. If answers are unavailable, state an ordering and workload assumption explicitly, then design against them.',
  },
  {
    id: 'framework-estimates',
    title: 'Use rough numbers to test the shape',
    eyebrow: '03 · Scale estimates',
    summary: 'Estimate enough to expose a capacity or design decision.',
    body: [
      'Back-of-the-envelope figures can show whether one machine is plausible and which path deserves attention. Begin with active users, actions per user, peak-to-average traffic, item size, and retention. Derive approximate reads, writes, storage, and transfer; “millions of users” alone is not a workload.',
      'Keep units and assumptions visible. One million daily users opening a feed ten times suggests roughly ten million feed reads per day before accounting for peaks. The important finding may be that reads dominate writes. Recalculate when a key assumption changes, and validate rough estimates with real traffic.',
    ],
    takeaways: ['Estimate from behavior, data size, peaks, and retention.', 'Use numbers to compare options, not to hide uncertainty behind false precision.'],
    diagramId: 'framework-estimates',
    scenario: 'A product has one million accounts but no usage data. Can you size its feed service?',
    scenarioAnswer: 'Not yet. Ask about active users, read and write frequency, peaks, item and media size, and retention. Then compute order-of-magnitude request, storage, and transfer needs with stated assumptions.',
  },
  {
    id: 'framework-blueprint',
    title: 'Draw the smallest useful blueprint',
    eyebrow: '04 · High-level design',
    summary: 'Show major responsibilities and data movement before internal details.',
    body: [
      'Start with clients and the service boundary. Add components needed to explain primary behavior: an API or web tier, persistent store, and any cache, media store, or queue with a clear role. Arrows should show who sends a request, where a write lands, and who returns the result.',
      'Treat the blueprint as a shared hypothesis. Check it against requirements and rough numbers, then invite feedback. A box called “database” is enough when the open question is the request path. Choose schemas or algorithms when those details become the decision at hand.',
    ],
    takeaways: ['Every component should serve a stated requirement or constraint.', 'Agree on the overall shape before spending time on low-level details.'],
    diagramId: 'framework-blueprint',
    scenario: 'You need an initial design for posting and reading a feed. What belongs on the first diagram?',
    scenarioAnswer: 'Show clients, a service handling post and feed requests, persistent post storage, and the major data paths. Add other components only where the agreed scope needs them.',
  },
  {
    id: 'framework-flows',
    title: 'Walk through real requests',
    eyebrow: '05 · Concrete flows',
    summary: 'Trace writes and reads to find gaps that boxes alone conceal.',
    body: [
      'For a feed, follow one person publishing a post: request, validation, persistent write, and any work needed to make it visible. Then follow a friend opening the feed: find relevant posts, order them, and return a page. The paths may place different pressure on storage and computation.',
      'Use concrete examples to test the arrows. Ask what happens with an image, no recent posts, or a read just after a write. These reveal missing responsibilities and edge cases while the blueprint is cheap to change.',
    ],
    takeaways: ['Trace at least one important write and one read from start to response.', 'Concrete requests expose missing data movement and edge cases.'],
    diagramId: 'framework-flows',
    scenario: 'A diagram has a feed API and database, but nobody knows when a new post appears to friends. What is missing?',
    scenarioAnswer: 'Walk the publishing request into storage and the retrieval request back out. State whether visibility is immediate or follows background work, then update the flow and user experience.',
  },
  {
    id: 'framework-iterate',
    title: 'Invite feedback and revise the model',
    eyebrow: '06 · Collaboration',
    summary: 'Treat the first design as a proposal that improves through review.',
    body: [
      'Explain the reasoning behind each choice early. Teammates may know that a feature has another priority, an existing service already solves a problem, or a dependency cannot meet the proposed traffic. Such feedback should change the design when warranted.',
      'When feedback changes a requirement, update the assumptions and replay affected flows. Compare alternatives using the agreed goals. Record why a simpler launch design is enough or why extra complexity is justified, plus the signal that would trigger a later change.',
    ],
    takeaways: ['Ask for feedback while changes are inexpensive.', 'Revise assumptions, flows, and tradeoffs together when scope changes.'],
    diagramId: 'framework-iterate',
    scenario: 'A reviewer says posts must include video, although your draft only stores text. What now?',
    scenarioAnswer: 'Confirm whether video is required in the first release and at what scale. Revise storage, publishing, retrieval, and capacity assumptions; compare the resulting alternatives.',
  },
  {
    id: 'framework-deep-dive',
    title: 'Deep dive where risk is highest',
    eyebrow: '07 · Priority and tradeoffs',
    summary: 'Spend detail on the component most likely to determine the outcome.',
    body: [
      'After the blueprint is agreed, choose a critical component or bottleneck for closer study. It might be feed generation under heavy reads, short-link identifiers, or chat presence. Requirements, estimates, and feedback determine the target; equal detail across every box wastes time.',
      'Compare plausible approaches using workload and failure behavior. For each, explain what improves, what becomes more complex, and what measurement would distinguish the options. If current needs fit a simpler design, its lower operating cost belongs in the decision.',
    ],
    takeaways: ['Prioritize detail that resolves a requirement or major risk.', 'Compare alternatives and operational cost, not just happy-path speed.'],
    diagramId: 'framework-deep-dive',
    scenario: 'Estimates show feed reads greatly exceed writes. Which part deserves the next deep dive?',
    scenarioAnswer: 'Investigate feed assembly and repeated read work. Compare retrieval and precomputation choices against latency, write cost, storage, and staleness.',
  },
  {
    id: 'framework-review',
    title: 'Close with failure and the next change',
    eyebrow: '08 · Review and operate',
    summary: 'Summarize the design, its weak points, and how the team will know when to evolve it.',
    body: [
      'Revisit the main requirements and the path that satisfies each. Identify the likely bottleneck and a reasonable next improvement. Describe when the current proposal stops being enough instead of calling it final.',
      'Check failures and day-two operation: what happens when a dependency is unavailable, which metrics and logs reveal the problem, and how changes reach production safely. If usage grows tenfold, name the first assumption to remeasure. Capture open questions for the next review.',
    ],
    takeaways: ['Review failure, monitoring, rollout, and future capacity alongside features.', 'End with a concise recap and explicit triggers for change.'],
    diagramId: 'framework-review',
    scenario: 'The design supports today’s load, but a campaign may increase traffic tenfold. How do you close the review?',
    scenarioAnswer: 'Recap request paths and assumptions, identify the tier likely to saturate, specify metrics and a load test, and outline a next capacity step and failure plan.',
  },
];

export const frameworkQuestions: Question[] = [
  {
    id: 'fq01', stepId: 'framework-scope', difficulty: 'Apply',
    prompt: 'Someone asks you to design a “news feed.” What is the most useful first move?',
    options: ['Clarify users and core feed behaviors', 'Choose a distributed database', 'Draw five regions', 'Optimize ranking'],
    correctIndex: 0,
    explanation: 'A broad name does not establish the product. Clarifying behavior and scope makes later choices meaningful.',
  },
  {
    id: 'fq02', stepId: 'framework-scope', difficulty: 'Diagnose',
    prompt: 'A team designs recommendations before learning the first release needs only recent friends’ posts. What went wrong?',
    options: ['The API format was missing', 'The design began before scope was agreed', 'Storage was estimated too early', 'More replicas were needed'],
    correctIndex: 1,
    explanation: 'A scope check would have separated the first release from a later recommendation feature.',
  },
  {
    id: 'fq03', stepId: 'framework-requirements', difficulty: 'Recall',
    prompt: 'Which is a quality requirement?',
    options: ['A user can view a feed', 'A post can include an image', 'Feed reads meet a latency target at peak traffic', 'A user can publish a post'],
    correctIndex: 2,
    explanation: 'Latency under load constrains how well a behavior works; the other choices describe product behaviors.',
  },
  {
    id: 'fq04', stepId: 'framework-requirements', difficulty: 'Apply',
    prompt: 'Feed ordering is unspecified. What should you do?',
    options: ['Silently choose ranked order', 'Skip the read path', 'Choose the most complex option', 'Ask and record an explicit assumption if needed'],
    correctIndex: 3,
    explanation: 'Ordering changes retrieval. Make the uncertainty visible and confirm or revisit the assumption.',
  },
  {
    id: 'fq17', stepId: 'framework-requirements', difficulty: 'Diagnose',
    prompt: '“Users can attach a photo” and “photos remain available after one storage node fails” describe which two kinds of requirement?',
    options: ['A feature, then a quality constraint', 'Two feature requirements', 'Two capacity estimates', 'A quality constraint, then a feature'],
    correctIndex: 0,
    explanation: 'Attaching a photo is observable product behavior. Surviving a node failure describes the required durability or availability of that behavior.',
  },
  {
    id: 'fq05', stepId: 'framework-estimates', difficulty: 'Apply',
    prompt: 'What extra information best turns a count of registered accounts into a read-traffic estimate?',
    options: ['Daily active users and feed opens per active user', 'Database table count', 'CSS framework', 'Engineering team size'],
    correctIndex: 0,
    explanation: 'Registered accounts do not indicate request rate. Active usage and frequency do.',
  },
  {
    id: 'fq06', stepId: 'framework-estimates', difficulty: 'Diagnose',
    prompt: 'Ten million daily reads average about 116 per second. Why is 116 requests per second an unsafe capacity target?',
    options: ['It omits user interface details', 'It omits peaks and headroom', 'It omits database names', 'It omits API paths'],
    correctIndex: 1,
    explanation: 'Traffic is uneven. Capacity must account for peaks, growth, and uncertainty.',
  },
  {
    id: 'fq07', stepId: 'framework-blueprint', difficulty: 'Apply',
    prompt: 'What should each component establish in the first blueprint?',
    options: ['Every schema field', 'Deployment commands', 'Its purpose and the data path through it', 'Its final vendor and size'],
    correctIndex: 2,
    explanation: 'The first diagram establishes responsibilities and flow. Details follow where they resolve a decision.',
  },
  {
    id: 'fq08', stepId: 'framework-blueprint', difficulty: 'Diagnose',
    prompt: 'A draft has a queue, cache, and CDN, but their roles are unclear. What should change?',
    options: ['Add more services', 'Make every arrow bidirectional', 'Choose a schema first', 'Justify or remove each against requirements and workload'],
    correctIndex: 3,
    explanation: 'Unjustified components obscure the design and add operating cost.',
  },
  {
    id: 'fq09', stepId: 'framework-flows', difficulty: 'Apply',
    prompt: 'Which pair of walkthroughs best tests a simple feed design?',
    options: ['Publish one post and retrieve a friend’s feed', 'Deploy a server and rotate a password', 'Open a dashboard and change a theme', 'Estimate a bill and choose a font'],
    correctIndex: 0,
    explanation: 'A write and a read exercise the core behaviors and expose how data is stored, found, and returned.',
  },
  {
    id: 'fq10', stepId: 'framework-flows', difficulty: 'Diagnose',
    prompt: 'A stored post never appears in a friend’s feed. What did the blueprint likely omit?',
    options: ['A CSS layout', 'A path from stored post to feed retrieval', 'A database icon', 'A DNS record'],
    correctIndex: 1,
    explanation: 'Walking the read after the write exposes whether retrieval can discover the new post.',
  },
  {
    id: 'fq11', stepId: 'framework-iterate', difficulty: 'Apply',
    prompt: 'Feedback adds video to a text-only post feature. What is the best response?',
    options: ['Add a CDN without considering upload', 'Discard all earlier decisions', 'Confirm scope and revise assumptions, flows, and estimates', 'Keep the original design'],
    correctIndex: 2,
    explanation: 'Media affects several parts of the design. Confirm the change, update the model, and explain tradeoffs.',
  },
  {
    id: 'fq12', stepId: 'framework-iterate', difficulty: 'Diagnose',
    prompt: 'A reviewer points out an existing media service, but the team insists on building another without comparison. What failed?',
    options: ['Estimating active users', 'Drawing a client arrow', 'Naming the release', 'Using feedback to compare and revise'],
    correctIndex: 3,
    explanation: 'Existing capabilities affect cost and feasibility. Review should test the proposal against new information.',
  },
  {
    id: 'fq13', stepId: 'framework-deep-dive', difficulty: 'Apply',
    prompt: 'How should you choose what to examine after agreeing on the blueprint?',
    options: ['Pick the component tied to a major requirement or risk', 'Explain every box equally', 'Start with the easiest box', 'Choose the newest technology'],
    correctIndex: 0,
    explanation: 'Focused detail is useful where it resolves a decision or risk.',
  },
  {
    id: 'fq14', stepId: 'framework-deep-dive', difficulty: 'Diagnose',
    prompt: 'A proposal adds a distributed subsystem for a workload one server handles comfortably. What cost is overlooked?',
    options: ['Product naming', 'Operational complexity relative to benefit', 'API endpoint count', 'Diagram appearance'],
    correctIndex: 1,
    explanation: 'More components require deployment, monitoring, failure handling, and maintenance.',
  },
  {
    id: 'fq15', stepId: 'framework-review', difficulty: 'Apply',
    prompt: 'What belongs in the closing review of a design that meets today’s needs?',
    options: ['Only the happy path', 'Immediate sharding of every database', 'Bottlenecks, failure, metrics, rollout, and change triggers', 'A claim it is complete forever'],
    correctIndex: 2,
    explanation: 'Review the operating and evolution path as well as the feature flow.',
  },
  {
    id: 'fq16', stepId: 'framework-review', difficulty: 'Diagnose',
    prompt: 'Traffic may grow tenfold, but the first saturated tier is unknown. What is a sound next step?',
    options: ['Add every scaling technique', 'Assume the database fails first', 'Wait for an outage', 'Measure and load-test current paths against the growth assumption'],
    correctIndex: 3,
    explanation: 'Measurements locate the constraint and guide a proportionate change.',
  },
  {
    id: 'fq18', stepId: 'framework-review', difficulty: 'Recall',
    prompt: 'Which sequence captures the framework used throughout this chapter?',
    options: ['Choose a database, add a cache, add regions, then review', 'Clarify scope, sketch a high-level design, deep dive, then review', 'Pick infrastructure, estimate cost, launch, then document', 'Deep dive, launch, gather requirements, then draw a diagram'],
    correctIndex: 1,
    explanation: 'The process moves from understanding the problem to a shared blueprint, focused detail, and a review of risks and next steps.',
  },
];
