import type { Question, Step } from './chapter';

export const keyValueSteps: Step[] = [
  {
    id:'kv-contract', title:'Define the key-value contract', eyebrow:'01 · Access pattern',
    summary:'A small API still needs precise durability, size, and consistency promises.',
    body:[
      'A key-value store associates a unique key with an opaque value. Its core operations are put(key, value) and get(key). Deletion, conditional writes, expiration, and listing are separate product decisions. Direct lookup by known key is its strength; arbitrary joins or filtering across values need another index or data model.',
      'Agree on key and value sizes, volume, read/write mix, latency, availability, durability, and whether a read must reflect the latest acknowledged write. A one-machine hash table is a useful first model, but a data set larger than one machine or machine failure forces distribution and recovery into the contract.',
    ],
    takeaways:['A key identifies an opaque value; the access pattern drives the design.','Specify durability, failure, and read-after-write expectations before choosing machinery.'],
    diagramId:'kv-contract',
    scenario:'Orders are stored by order ID, but a team also needs all late orders in a region. What would you clarify?',
    scenarioAnswer:'Direct order-ID lookup fits a key-value API. Late orders by region need a maintained secondary index or a query-oriented store; scanning every opaque value is not a scalable substitute.',
  },
  {
    id:'kv-partition', title:'Partition the key space', eyebrow:'02 · Data placement',
    summary:'Give each key a predictable home while limiting movement when nodes change.',
    body:[
      'Hash each key to a partition and route requests to its owner. Consistent hashing places keys and node positions on a ring; a key maps to the next owner clockwise. Virtual nodes distribute ownership more evenly and let larger machines take more ranges. Clients or coordinators need a current membership map during changes.',
      'When a node joins, only ranges it takes need to move. That transfer still costs network and disk capacity. Watch for hot keys: balanced key counts do not guarantee balanced request load. Replication and caching can help reads, but a write-hot key may require a different data model.',
    ],
    takeaways:['Partitioning distributes data; it does not create a safety copy.','Virtual nodes balance ranges, while hot keys need workload-specific treatment.'],
    diagramId:'kv-partition',
    scenario:'One key receives a third of all writes, though key counts are evenly distributed. Will more virtual nodes solve it?',
    scenarioAnswer:'No. Virtual nodes balance ranges, but that key still has one logical home. Consider splitting the logical write across keys or changing the write model.',
  },
  {
    id:'kv-replication', title:'Replicate across failure domains', eyebrow:'03 · Copies and placement',
    summary:'Keep independent physical copies so one node does not own the only durable value.',
    body:[
      'For each key choose N distinct physical replicas, often by walking a placement ring. A coordinator sends reads and writes to them. Distinct virtual nodes on one machine are not distinct safety copies. Place copies across independent racks or data centers when those failures are in scope, and budget for extra storage and write traffic.',
      'Copies can temporarily differ. Partitioning answers where a key belongs; replication answers where additional copies belong. Neither alone defines when put() acknowledges success or which version get() returns.',
    ],
    takeaways:['N counts independent physical replicas.','Failure-domain placement matters as much as copy count.'],
    diagramId:'kv-replication',
    scenario:'Three virtual-node copies sit on one physical server. Does N = 3 protect against its failure?',
    scenarioAnswer:'No. That failure removes all copies. Select three distinct physical owners and spread them across the failure domains in the availability goal.',
  },
  {
    id:'kv-quorum', title:'Choose read and write acknowledgments', eyebrow:'04 · Consistency tradeoff',
    summary:'W and R determine how many replicas a coordinator waits for.',
    body:[
      'Let N be replica count, W required write acknowledgments, and R required read responses. With N = 3 and W = R = 2, every fixed read and write set intersects. Waiting for more responses raises latency and can lower availability when links or replicas fail. W = 1 acknowledges quickly but leaves a larger stale-read and data-loss window.',
      'The familiar W + R > N rule provides overlap under a stable replica set, but does not alone make arbitrary concurrent writes linearizable. Sloppy quorums, changing membership, version selection, and races need further rules. During a network partition decide which operations can proceed and which freshness guarantee must hold.',
    ],
    takeaways:['W + R > N gives overlap for fixed replica sets, subject to assumptions.','Tune quorum settings to latency, freshness, and failure needs.'],
    diagramId:'kv-quorum',
    scenario:'N = 3, W = 1, R = 1. A write succeeds on one node and a read goes to a different node. What can happen?',
    scenarioAnswer:'The read may return an older value before replication reaches it. If immediate visibility matters, use stronger coordination or a session-level read-after-write path.',
  },
  {
    id:'kv-conflicts', title:'Resolve concurrent versions', eyebrow:'05 · Causality',
    summary:'Independent writers can update the same key without one obvious winner.',
    body:[
      'Two clients can read one version, change it differently, and write nearly together. Last-write-wins is simple but can discard an accepted update, especially when clocks disagree. Compare-and-set can reject a stale edit; another design exposes sibling versions for application reconciliation. A preference, a cart, and a balance require different policies.',
      'Vector clocks or related metadata distinguish descendants from concurrent siblings. If one version includes every causal update in another, it can replace its ancestor. Incomparable versions need a merge. Metadata size, tombstones, retries, and client logic add cost. A vector clock detects conflict; it cannot decide the business outcome.',
    ],
    takeaways:['Concurrent writes can both be accepted without a single correct timestamp winner.','Causal metadata detects conflicts; domain rules resolve them.'],
    diagramId:'kv-conflicts',
    scenario:'Two offline devices edit an account balance. Should the store silently retain the newest wall-clock value?',
    scenarioAnswer:'No. That could discard money movement. Use stronger transactional or ledger semantics for balances, with explicit reconciliation.',
  },
  {
    id:'kv-failure', title:'Serve through temporary failure', eyebrow:'06 · Detection and handoff',
    summary:'Failure suspicion, substitute replicas, and recovery each need a plan.',
    body:[
      'Nodes can share membership and heartbeat observations through gossip. One missed heartbeat is suspicion, not proof: slow links and overloaded machines can look dead. Use multiple observations and appropriate timeouts, then update routing without a single membership dependency.',
      'A sloppy quorum can use healthy substitute nodes when preferred replicas are unreachable. Hinted handoff stores a temporary copy tagged with its target owner and sends it back after recovery. This helps availability, but weakens simple fixed-set quorum reasoning. Hints can expire or fail, so they cannot be the only repair process.',
    ],
    takeaways:['Failure detection is uncertain under delay.','Hints bridge temporary outages; they do not replace durable repair.'],
    diagramId:'kv-failure',
    scenario:'A preferred replica is gone for hours and the substitute holding hints also fails. What assumption breaks?',
    scenarioAnswer:'Hinted handoff was treated as durable recovery. Maintain enough durable copies and use anti-entropy to rebuild missing ranges.',
  },
  {
    id:'kv-repair', title:'Repair replica drift', eyebrow:'07 · Anti-entropy',
    summary:'Compare data efficiently so long-lived divergence does not become permanent.',
    body:[
      'Periodic anti-entropy compares replicas responsible for the same range. A Merkle tree hashes groups of keys and values upward. Matching hashes skip entire subtrees; mismatches narrow the ranges that need transfer. The tree detects differences, but does not decide which value is authoritative.',
      'Repair needs version and deletion metadata. A deleted key needs a tombstone retained long enough to stop an old replica from resurrecting it. Measure repair lag and bytes transferred, and rate-limit background repair so foreground traffic remains healthy. Multi-data-center survival also needs cross-site copies and recovery drills.',
    ],
    takeaways:['Merkle comparisons narrow the ranges that differ.','Tombstones and version choice make convergence safe.'],
    diagramId:'kv-repair',
    scenario:'A replica returns after missing a delete, and its old value reappears. What was missing?',
    scenarioAnswer:'A retained versioned tombstone. Repair must propagate the delete instead of treating the stale value as new data.',
  },
  {
    id:'kv-paths', title:'Trace a local read and write', eyebrow:'08 · Storage engine',
    summary:'Durable acknowledgment depends on the path inside a replica.',
    body:[
      'A log-structured replica commonly appends a write to a durable log and updates an in-memory table. It later flushes sorted tables to disk. Acknowledging before the required log durability boundary risks losing a write on restart, even if the coordinator counted it. Compaction merges files and clears obsolete versions at an I/O cost.',
      'A read checks memory and then disk tables. Bloom filters can say a table definitely lacks a key or might contain it; a possible hit still needs lookup. Observe log durability, flush and compaction pressure, read amplification, and disk headroom alongside API latency.',
    ],
    takeaways:['Replica acknowledgments need an explicit durability boundary.','Bloom filters rule out misses; they do not prove presence.'],
    diagramId:'kv-paths',
    scenario:'A node acknowledges when a value reaches memory but before its log is durable. Power fails immediately. What happens?',
    scenarioAnswer:'That replica may lose an acknowledged value. Count it toward W only after the durability boundary promised by the API.',
  },
  {
    id:'kv-operations', title:'Test the promises under failure', eyebrow:'09 · Operate the system',
    summary:'Routing, convergence, and durability must remain observable under stress.',
    body:[
      'Measure tail latency, unavailable operations, hot ranges, replica lag, hint backlog, repair age, compaction pressure, and capacity by failure domain. Test node loss, network partitions, membership changes, and data-center loss against the declared W/R policy. A green get() latency chart can hide a replica that has not converged.',
      'Choose a policy for a real workload. A low-risk cache-like value may accept eventual convergence. Inventory reservations and money movement require stronger coordination and business invariants. Document retry behavior, idempotency, and ambiguous acknowledgments so clients do not accidentally duplicate operations.',
    ],
    takeaways:['Verify behavior during partitions and recovery, not only healthy throughput.','Tie consistency and durability to specific product invariants.'],
    diagramId:'kv-operations',
    scenario:'Normal latency is low but hint backlog grows for days. Is the system healthy?',
    scenarioAnswer:'No. Replicas may remain stale or recovery data may be at risk. Investigate backlog age, repair progress, and at-risk copies.',
  },
];

export const keyValueQuestions: Question[] = [
  {id:'kvq01',stepId:'kv-contract',difficulty:'Recall',prompt:'Which operation is native to a simple key-value API?',options:['Join orders with customers','Get a value by known key','Filter every value by a field','Sort all values by date'],correctIndex:1,explanation:'The API efficiently retrieves an opaque value from a known key.'},
  {id:'kvq02',stepId:'kv-contract',difficulty:'Diagnose',prompt:'A team has not decided whether acknowledged writes must survive a machine failure. What is missing?',options:['A color palette','A durability requirement','A browser cache','A page size'],correctIndex:1,explanation:'Acknowledgment and recovery semantics shape replication and local logging.'},
  {id:'kvq03',stepId:'kv-partition',difficulty:'Recall',prompt:'What does partitioning primarily solve?',options:['It makes every value strongly consistent','It distributes a data set across owners','It eliminates all hot keys','It creates backup copies'],correctIndex:1,explanation:'Partitioning assigns key ranges to owners so a large data set spans machines.'},
  {id:'kvq04',stepId:'kv-partition',difficulty:'Apply',prompt:'A server joins a consistent-hash ring. Which data should normally move?',options:['Every key','Ranges assigned to the new owner','Only cached values','Nothing until failure'],correctIndex:1,explanation:'Consistent hashing limits movement to ranges whose ownership changes.'},
  {id:'kvq05',stepId:'kv-replication',difficulty:'Diagnose',prompt:'Three copies are on one physical host. What is the issue?',options:['Reads become impossible','A host failure removes every copy','Keys cannot be hashed','The API must change'],correctIndex:1,explanation:'Replicas need independent physical owners for host failure tolerance.'},
  {id:'kvq06',stepId:'kv-replication',difficulty:'Recall',prompt:'How do partitioning and replication differ?',options:['Both only compress data','Partitioning assigns keys; replication makes copies','Replication decides query syntax','Partitioning guarantees durability'],correctIndex:1,explanation:'Placement and copy count answer different questions.'},
  {id:'kvq07',stepId:'kv-quorum',difficulty:'Apply',prompt:'With N = 3, W = 2, R = 2 on a fixed replica set, what is guaranteed?',options:['Read and write sets share a replica','Every replica answers each read','All concurrent writes are linearizable','No read can fail'],correctIndex:0,explanation:'W + R exceeds N, so the sets intersect; stronger semantics need more rules.'},
  {id:'kvq08',stepId:'kv-quorum',difficulty:'Diagnose',prompt:'Why can W = 1 and R = 1 return stale data after a write?',options:['The ring stops working','The read can reach a different, lagging replica','Bloom filters always lie','The key becomes non-unique'],correctIndex:1,explanation:'One replica may acknowledge before another receives the change.'},
  {id:'kvq09',stepId:'kv-quorum',difficulty:'Diagnose',prompt:'Why is W + R > N insufficient alone for linearizable reads?',options:['Overlap never occurs','Sloppy placement, concurrency, and version choice need rules','N must be even','R must equal W'],correctIndex:1,explanation:'Overlap helps, but full semantics require stable membership and handling of races.'},
  {id:'kvq10',stepId:'kv-conflicts',difficulty:'Recall',prompt:'What can vector-clock-style metadata reveal?',options:['The correct business value','Whether versions are ordered or concurrent','The fastest data center','Precise wall-clock time'],correctIndex:1,explanation:'Causal metadata distinguishes descendants and siblings, but does not choose a merge.'},
  {id:'kvq11',stepId:'kv-conflicts',difficulty:'Apply',prompt:'Two clients edit a cart from one original version. Which approach preserves both edits for reconciliation?',options:['Keep the newest timestamp','Return sibling versions','Discard the original key','Move partitions'],correctIndex:1,explanation:'Siblings preserve concurrent outcomes for domain-aware merging.'},
  {id:'kvq12',stepId:'kv-failure',difficulty:'Diagnose',prompt:'A node misses one heartbeat. What should peers conclude?',options:['It is certainly dead','It may be delayed; gather more evidence','Delete its data','Stop all requests'],correctIndex:1,explanation:'Delay and overload can mimic failure.'},
  {id:'kvq13',stepId:'kv-failure',difficulty:'Apply',prompt:'What is hinted handoff intended to do?',options:['Index value fields','Return substitute-held updates to a recovered owner','Guarantee linearizability','Replace repair forever'],correctIndex:1,explanation:'A substitute retains temporary hints for a preferred owner.'},
  {id:'kvq14',stepId:'kv-repair',difficulty:'Recall',prompt:'What does a Merkle tree help replicas do?',options:['Choose a business merge','Locate differing ranges efficiently','Guarantee no false positives','Generate client keys'],correctIndex:1,explanation:'Hierarchical hashes skip matching ranges.'},
  {id:'kvq15',stepId:'kv-repair',difficulty:'Diagnose',prompt:'An old value reappears when a node missing a delete rejoins. What failed?',options:['API syntax','Deletion metadata expired before safe repair','Virtual nodes','TCP'],correctIndex:1,explanation:'A retained tombstone carries the deletion version.'},
  {id:'kvq16',stepId:'kv-paths',difficulty:'Apply',prompt:'When should a replica count toward a durable write acknowledgment?',options:['After volatile memory only','After required log persistence','After all future compaction','After Bloom filter maybe'],correctIndex:1,explanation:'The required log durability boundary must be reached first.'},
  {id:'kvq17',stepId:'kv-paths',difficulty:'Recall',prompt:'What does a Bloom filter say about a disk table?',options:['Definitely present','Definitely absent or maybe present','Latest value is correct','Compaction is needed'],correctIndex:1,explanation:'It can have false positives but rules out absent keys.'},
  {id:'kvq18',stepId:'kv-operations',difficulty:'Diagnose',prompt:'Latency is low but hint backlog age rises. What should operators inspect?',options:['CSS','Replica convergence and repair risk','DNS only','Key string type'],correctIndex:1,explanation:'Old hints imply stale replicas and recovery risk.'},
  {id:'kvq19',stepId:'kv-operations',difficulty:'Apply',prompt:'Which test validates a multi-region survival target?',options:['Healthy-read benchmark only','Simulate losing a region and verify routing, quorum, recovery','Count source files','Add virtual nodes'],correctIndex:1,explanation:'The target concerns regional failure behavior.'},
];
