import type { Question, Step } from './chapter';

export const feedSteps: Step[] = [
  {
    id: 'feed-scope', title: 'Define the feed promise', eyebrow: '01 · Product boundary',
    summary: 'Agree on who can publish, who may read, and how fresh the timeline must feel.',
    body: [
      'A feed is a personalized view of posts, not a single shared list. For this design, people publish text with optional images or video, follow other accounts, and read a home timeline on mobile or web. Assume a reverse chronological first release with a few thousand follows per typical account. Search, ads, stories, and recommendations can be separate designs.',
      'Ask whether follows require approval, whether posts can be private, and what a block or mute means. State a freshness goal for ordinary posts, the peak publish and refresh rates, active readership, expected media size, and how far people scroll. A celebrity with millions of followers changes the write workload even if they publish rarely.',
      'Keep three operations distinct: accepting a post durably, making it eligible in followers’ feeds, and rendering a feed page. A successful publish response need not mean every follower has already received an entry; the product must say what delay is acceptable.',
    ],
    takeaways: ['Define audience and visibility before choosing fanout.', 'Separate durable publishing, feed eligibility, and page rendering.'],
    diagramId: 'feed-scope',
    scenario: 'The brief says “show friends’ posts instantly.” Which promises need precise definitions before sizing a design?',
    scenarioAnswer: 'Clarify follow or friendship rules, private audiences, ranking versus recency, acceptable post-to-feed delay, peak active readers and publishers, and how much media is included. “Instant” needs a measurable target.',
  },
  {
    id: 'feed-publish', title: 'Commit the post before fanout', eyebrow: '02 · Publish path',
    summary: 'Keep one canonical post, then distribute lightweight references asynchronously.',
    body: [
      'The publisher sends text, media references, and an idempotency key. The API authenticates the account, checks the rate limit and audience, validates media readiness, and stores one canonical post with a server ID and creation time. A retry using the same key returns the same post rather than publishing twice.',
      'After commit, an event enters a durable queue. Fanout workers read a versioned follow graph and write eligible post IDs into timeline stores. The publish API does not wait for thousands of follower writes. If the queue stalls, the canonical post survives; workers can catch up from a durable event stream or outbox.',
      'An event emitted before the database commit can point to a post that does not exist. A commit followed by a failed enqueue can hide a valid post from feeds. A transactional outbox or equivalent durable handoff closes that gap; the worker and inbox insertion must tolerate retries.',
    ],
    takeaways: ['A canonical post is the source of truth; feed entries are derived references.', 'Use a reliable post-to-queue handoff and idempotent fanout.'],
    diagramId: 'feed-publish',
    scenario: 'The post row is saved, but the fanout process crashes before enqueueing work. What prevents a permanently missing feed entry?',
    scenarioAnswer: 'Record the fanout intent durably with the post, such as an outbox row in the same transaction. A publisher can later move that intent to the queue; workers deduplicate by post and recipient.',
  },
  {
    id: 'feed-media', title: 'Keep media off the post row', eyebrow: '03 · Media path',
    summary: 'Store post metadata and media bytes in systems suited to their different access patterns.',
    body: [
      'The client uploads images or video to object storage through a controlled upload path. Processing workers can scan, resize, or transcode the files before a post references a ready media object. The post database retains metadata, ownership, and object keys; it does not carry large video bytes through every feed query.',
      'A CDN serves approved variants near readers. The feed API returns media URLs or tokens alongside post metadata; the browser fetches the bytes separately. Private media requires an authorization-aware delivery strategy, such as short-lived signed access, rather than assuming a public CDN URL is safe.',
      'If upload succeeds but publishing fails, clean up the unreferenced object after a grace period. If processing is delayed, show an explicit pending state or postpone publication according to the product promise. Deleting a post must also make cached media inaccessible within the required revocation window.',
    ],
    takeaways: ['Object storage holds bytes; post storage holds ownership and references.', 'A CDN improves delivery, while privacy and cleanup still need explicit rules.'],
    diagramId: 'feed-media',
    scenario: 'A private video is deleted, but its old CDN URL still works. Which boundary failed?',
    scenarioAnswer: 'The delivery path did not revoke access promptly enough. Invalidate or expire cached access, use short-lived authorized URLs where appropriate, and tie the media lifecycle to post visibility.',
  },
  {
    id: 'feed-fanout', title: 'Choose where fanout happens', eyebrow: '04 · Distribution strategy',
    summary: 'Push common posts to inboxes, pull very large audiences at read time, and mix both when needed.',
    body: [
      'Fanout on write adds a post ID to each eligible follower’s timeline as the author publishes. Reads become cheap because the candidate list is ready, but a high-follower author creates many writes and inactive followers consume needless work. Fanout on read queries followed authors’ recent posts when a reader opens the feed, reducing idle writes but increasing read latency and merge cost.',
      'A hybrid pushes ordinary authors to follower inboxes and leaves very large authors in their own recent-post indexes. At read time the feed service merges the reader’s inbox with recent posts from those high-follower authors. The threshold is a measured choice based on follower count, active-reader fraction, publish rate, fanout lag, and read latency.',
      'Avoid treating a follower count as a complete cost estimate. One million inactive followers differ from one million readers refreshing now. Bound work with queue partitions, per-author limits, and backpressure. Changing an author between push and pull needs a transition rule so posts are neither absent nor shown twice.',
    ],
    takeaways: ['Write fanout trades extra writes for fast reads; read fanout does the reverse.', 'Hybrid fanout handles skew and must define deduplication during strategy changes.'],
    diagramId: 'feed-fanout',
    scenario: 'A musician with 20 million followers publishes twice a day. Most followers open the app weekly. Which fanout choice deserves testing?',
    scenarioAnswer: 'Pull the musician’s recent posts for active readers, or use a hybrid that selectively pushes to active followers. Pushing 20 million entries per post wastes work for inactive accounts; validate the resulting read merge latency.',
  },
  {
    id: 'feed-read', title: 'Assemble one feed page', eyebrow: '05 · Retrieval path',
    summary: 'Gather candidate IDs, enforce current visibility, hydrate post data, and return a stable page.',
    body: [
      'A feed request identifies the reader and carries a cursor and page size. The service obtains precomputed inbox IDs, merges any pull-source posts, removes duplicate IDs, and takes a bounded candidate window. It then checks current follow, block, mute, deletion, and audience rules before fetching post and author details from caches or durable stores.',
      'For a reverse chronological feed, order by a server timestamp plus a unique post ID to break ties. Encode that position in an opaque cursor. Offset pagination can skip or repeat entries when fresh posts arrive ahead of page two. A cursor makes scrolling more stable, though visibility changes can still remove items between requests.',
      'Cache the hot head of each timeline and popular post or author objects, but keep the canonical post and relationship state durable. If the cache misses, rebuild a bounded page from indexes; a cold cache should degrade latency, not erase posts. Return media references rather than media bytes.',
    ],
    takeaways: ['An inbox contains candidates, not the final authorized response.', 'Use a stable cursor and bounded hydration to keep reads predictable.'],
    diagramId: 'feed-read',
    scenario: 'A blocked author’s ID remains in the reader’s cached inbox. What should the read service do?',
    scenarioAnswer: 'Filter the candidate against current block and audience rules before hydration and response. Then repair or invalidate the stale inbox entry asynchronously; cached membership must not grant access.',
  },
  {
    id: 'feed-ranking', title: 'Separate candidates from order', eyebrow: '06 · Ranking decision',
    summary: 'Start with recency, then add ranking without making the source of truth depend on a score.',
    body: [
      'Chronological ordering makes the first version easy to reason about: newest eligible posts appear first. A ranked feed changes the product goal. The candidate stage still gathers allowed posts, but a ranking stage scores a bounded set using signals such as relationship strength, freshness, and prior interactions. The score is a derived value and may change as behavior changes.',
      'Do not rank before access checks: a high score cannot make a private post visible. A ranking system also needs diversity, quality, and abuse controls; otherwise engagement signals can amplify spam. State whether the learner is designing a chronological feed or a ranked one, because the storage and pagination choices differ.',
      'For ranked pagination, pin a feed session, snapshot candidate set, or carry an opaque continuation token that captures enough ordering state. Recomputing all scores between pages can reorder items and produce duplicates or gaps. Measure both relevance and freshness, not only click rate.',
    ],
    takeaways: ['Candidate selection, authorization, and ranking are distinct stages.', 'Ranked pagination needs an ordering contract across successive pages.'],
    diagramId: 'feed-ranking',
    scenario: 'A product switches from newest-first to “most relevant.” Why might the old timestamp cursor produce repeated posts?',
    scenarioAnswer: 'Scores can move independently of creation time. A timestamp cursor no longer describes the ranked order; use a feed-session snapshot or continuation token tied to ranking state.',
  },
  {
    id: 'feed-privacy', title: 'Repair derived state when rules change', eyebrow: '07 · Consistency and deletion',
    summary: 'Treat timeline entries as disposable pointers and recheck access at the final read boundary.',
    body: [
      'A user may unfollow, mute, block, change a post’s audience, or delete it after fanout. Existing inbox entries and caches can lag. The read service must enforce the current authorization policy against canonical relationship and post state before returning content. Background invalidation removes stale pointers and reduces future work, but it is not the privacy boundary.',
      'Set distinct guarantees: post creation can appear eventually in a follower’s feed; deletion or a privacy change may require much faster suppression. Tombstones prevent a deleted post from reappearing when a delayed worker retries. Versioned audience or relationship data helps workers detect work produced under an older rule.',
      'A post may already be on a device or in a CDN cache. Document the practical revocation window and purge mechanism for media; no server-side cache policy can erase a screenshot or a client’s previously downloaded bytes. “Delete” needs a product-specific retention and audit policy as well as an API behavior.',
    ],
    takeaways: ['Feed cache entries never override current access rules.', 'Creation and revocation may need different consistency targets.'],
    diagramId: 'feed-privacy',
    scenario: 'A private post was fanned out, then the author removes a follower while a queue is delayed. What must hold at read time?',
    scenarioAnswer: 'The removed follower must fail the current audience check even if an old fanout job writes the post ID into their inbox. Tombstones or version checks can clean derived entries, but read-time authorization closes the privacy gap.',
  },
  {
    id: 'feed-operations', title: 'Measure the feed that readers receive', eyebrow: '08 · Reliability and operations',
    summary: 'Watch publish-to-visible delay, queue lag, read latency, cache behavior, and privacy failures.',
    body: [
      'Define service-level signals across the complete path: post commit success, event handoff failures, fanout queue age, percentage of eligible followers seeing a post within the freshness target, feed first-page latency, cache hit rate, empty-feed rate, and media error rate. A healthy post API with hours of fanout lag is still a broken feed.',
      'Retry workers with idempotent post-recipient keys and dead-letter handling for poison events. If the inbox cache or store is unavailable, offer a bounded pull from canonical recent-post indexes for a degraded first page if capacity allows. Limit that fallback so a broad cache outage does not overload the post database.',
      'Skew matters: a high-follower publisher can produce a burst even at a modest global posts-per-second rate. Partition work, cap concurrency, and monitor per-author hotspots. Reconcile sampled inboxes against canonical posts to detect lost fanout or duplicate entries. Revisit read and write fanout thresholds using observed activity, not a fixed rule from the diagram.',
    ],
    takeaways: ['Observe user-visible freshness and latency, not only API status.', 'Retries, bounded fallback, and reconciliation make derived feeds recoverable.'],
    diagramId: 'feed-operations',
    scenario: 'Publish success is 99.99%, but followers report that posts arrive an hour late. Which signal reveals the fault?',
    scenarioAnswer: 'Publish-to-visible delay and the age of the oldest fanout job reveal the gap. Inspect queue backlog, worker throughput, per-author hotspots, and post-to-queue handoff before adding more web servers.',
  },
];

export const feedQuestions: Question[] = [
  {id:'feed-q01',stepId:'feed-scope',difficulty:'Recall',prompt:'Which operation should “publish succeeded” guarantee first?',options:['Every follower has opened the post','The canonical post is durably accepted','The post has reached every CDN edge','Ranking scores have settled'],correctIndex:1,explanation:'Durable acceptance can be acknowledged before asynchronous fanout and delivery finish.'},
  {id:'feed-q02',stepId:'feed-scope',difficulty:'Apply',prompt:'A new feed brief never says whether private accounts exist. Why ask before drawing a cache?',options:['It changes font sizes','It removes all need for a database','Visibility affects fanout and read authorization','Private accounts cannot upload media'],correctIndex:2,explanation:'Audience rules affect which inboxes receive candidate IDs and what the read service may return.'},
  {id:'feed-q03',stepId:'feed-scope',difficulty:'Diagnose',prompt:'A team sizes fanout from 10 million registered users alone. What key workload measure is missing?',options:['Publisher follower distribution and active readership','The color of the timeline','The number of SVG icons','The shortest username'],correctIndex:0,explanation:'Follower skew and active readers determine distribution work and read demand much more directly than registrations.'},
  {id:'feed-q04',stepId:'feed-publish',difficulty:'Recall',prompt:'Why store post IDs in follower inboxes rather than full post copies?',options:['IDs are always globally ordered','Media cannot be shown otherwise','It makes the API synchronous','The canonical record stays singular while derived entries remain small'],correctIndex:3,explanation:'Small references reduce fanout storage and allow post data to be hydrated from its canonical source or cache.'},
  {id:'feed-q05',stepId:'feed-publish',difficulty:'Apply',prompt:'The post commits but enqueueing its fanout event fails. Which design repairs the handoff?',options:['Longer CDN TTL','A transactional outbox committed with the post','A shorter username','Disabling retries'],correctIndex:1,explanation:'A durable outbox preserves the intent so a relay can enqueue later without losing the post.'},
  {id:'feed-q06',stepId:'feed-publish',difficulty:'Diagnose',prompt:'An API timeout causes a client to retry and creates two posts. What was missing?',options:['A profile cache','A different sort order','A stable idempotency key tied to the publisher','A higher image resolution'],correctIndex:2,explanation:'The same logical submission should return its existing post ID when retried.'},
  {id:'feed-q07',stepId:'feed-media',difficulty:'Recall',prompt:'Where do the large image and video bytes belong?',options:['Object storage with processed variants for delivery','Every follower inbox row','A relationship graph edge','The page cursor'],correctIndex:0,explanation:'Object storage holds bytes; post records hold references and access metadata.'},
  {id:'feed-q08',stepId:'feed-media',difficulty:'Apply',prompt:'A private image is cached at an edge. What should govern future access?',options:['The image filename alone','A permanent public URL','The number of likes','A revocable or short-lived authorized delivery path'],correctIndex:3,explanation:'Private media cannot rely on an indefinitely reusable public URL after audience or deletion changes.'},
  {id:'feed-q09',stepId:'feed-media',difficulty:'Diagnose',prompt:'Thousands of abandoned uploads fill storage. Which lifecycle step is absent?',options:['Ranking calibration','Cleanup of unreferenced objects after a grace period','A reverse chronological index','Follower count caching'],correctIndex:1,explanation:'Uploads that never become posts need eventual garbage collection.'},
  {id:'feed-q10',stepId:'feed-fanout',difficulty:'Recall',prompt:'What does fanout on write buy?',options:['No derived state','Fast reads from precomputed recipient timelines','Zero work for inactive followers','Strict global ordering'],correctIndex:1,explanation:'The system pays write cost ahead of time to make candidate retrieval fast.'},
  {id:'feed-q11',stepId:'feed-fanout',difficulty:'Apply',prompt:'A high-follower account posts to mostly inactive followers. Which approach avoids millions of idle inbox writes?',options:['Copy full post bodies','Pin all content in CDN','Pull its recent posts at read time or selectively push to active readers','Disable pagination'],correctIndex:2,explanation:'Read fanout or hybrid delivery shifts work toward people who actually open the feed.'},
  {id:'feed-q12',stepId:'feed-fanout',difficulty:'Diagnose',prompt:'A creator moves from push to pull and one post appears twice. What transition rule is missing?',options:['Deduplication when merging inbox and pull sources','A new upload size limit','A different web framework','A cache with no TTL'],correctIndex:0,explanation:'The same post can exist in both candidate sources during a strategy change; merge by stable post ID.'},
  {id:'feed-q13',stepId:'feed-read',difficulty:'Recall',prompt:'What is a follower inbox entry in this design?',options:['Proof of permanent read permission','The complete media file','An unchangeable ranked score','A candidate post reference'],correctIndex:3,explanation:'The read service still checks current visibility and hydrates the candidate before returning it.'},
  {id:'feed-q14',stepId:'feed-read',difficulty:'Apply',prompt:'New posts arrive while someone loads page two. Which pagination method best avoids offset shifts?',options:['A larger fixed offset','A cursor based on stable order keys','Random page numbers','A client clock only'],correctIndex:1,explanation:'A server-order cursor anchors the next page to the prior page’s last item.'},
  {id:'feed-q15',stepId:'feed-read',difficulty:'Diagnose',prompt:'A muted author still appears because their ID was cached earlier. What must the read path add?',options:['More CDN edges','A higher cache TTL','Current relationship and visibility filtering','A fanout queue reset'],correctIndex:2,explanation:'A cached candidate is not sufficient permission to render a post.'},
  {id:'feed-q16',stepId:'feed-ranking',difficulty:'Recall',prompt:'What does the ranking stage operate on?',options:['A bounded set of eligible candidates','Raw private posts before access checks','CDN bytes','Only the author’s profile'],correctIndex:0,explanation:'Candidate gathering and authorization precede scoring and ordering.'},
  {id:'feed-q17',stepId:'feed-ranking',difficulty:'Apply',prompt:'A team adds ranking but keeps a pure creation-time cursor. What should it change?',options:['The image format','The follow graph data model only','The login form','Use a continuation token or snapshot tied to ranked order'],correctIndex:3,explanation:'Ranked scores can change independently of creation time, so chronological cursors no longer describe page boundaries.'},
  {id:'feed-q18',stepId:'feed-ranking',difficulty:'Diagnose',prompt:'Click rate rises while fresh posts disappear. What metric family was neglected?',options:['File naming','Freshness and diversity alongside relevance','The number of queue icons','HTTP method count'],correctIndex:1,explanation:'Engagement alone can favor old or repetitive content and hide new posts.'},
  {id:'feed-q19',stepId:'feed-privacy',difficulty:'Recall',prompt:'Where should final authorization be enforced?',options:['Only when a follow is created','Only during asynchronous fanout','On the feed read before content is returned','Only at the CDN'],correctIndex:2,explanation:'Derived timeline entries may be stale after privacy or relationship changes.'},
  {id:'feed-q20',stepId:'feed-privacy',difficulty:'Apply',prompt:'A deleted post is replayed from an old queue event. What protects the feed?',options:['A deletion tombstone or version check plus read filtering','A larger worker batch','A shorter page size alone','A permanent CDN URL'],correctIndex:0,explanation:'Workers and read paths must recognize that the canonical post is no longer eligible.'},
  {id:'feed-q21',stepId:'feed-privacy',difficulty:'Diagnose',prompt:'A blocked reader sees a cached private post. Which assumption failed?',options:['All posts need video transcodes','Cursors are too long','A load balancer needs more hosts','A precomputed inbox was treated as authorization'],correctIndex:3,explanation:'Inbox pointers are derived and can lag; current access must be checked at response time.'},
  {id:'feed-q22',stepId:'feed-operations',difficulty:'Recall',prompt:'Which measure best captures feed freshness?',options:['The number of source files','Time from post commit until an eligible follower can read it','Total accounts ever created','Post text length'],correctIndex:1,explanation:'This end-to-end delay includes event handoff, queueing, fanout, and retrieval.'},
  {id:'feed-q23',stepId:'feed-operations',difficulty:'Apply',prompt:'The inbox store fails for ten minutes. What is a responsible degraded mode?',options:['Return all private posts','Retry every request without limits','Build a bounded page from canonical recent-post indexes with capacity limits','Delete all queued fanout jobs'],correctIndex:2,explanation:'A bounded fallback can restore some feed access without overwhelming the canonical database.'},
  {id:'feed-q24',stepId:'feed-operations',difficulty:'Diagnose',prompt:'The publish API is healthy but fanout queue age climbs. Which capacity is likely constrained?',options:['Fanout worker throughput or a hot partition','The client font renderer','DNS domain registration','The media aspect ratio'],correctIndex:0,explanation:'Queue age rising despite successful publishes points to downstream event or worker backlog.'},
];
