import type { Question, Step } from './chapter';

export const notificationSteps: Step[] = [
  {
    id: 'notification-scope', title: 'Define the delivery promise', eyebrow: '01 · Requirements',
    summary: 'Name the channels, urgency, consent, and what “delivered” actually means.',
    body: [
      'A notification can be a mobile push, email, SMS, or an in-app item. They differ in cost, reach, payload, and what their providers can confirm. Start with the events worth sending: a payment alert may be urgent, while a weekly digest may wait. Record the expected daily volume, peak burst, permitted delay, supported devices, and markets.',
      'Use separate states for accepted by our service, handed to a provider, accepted by that provider, and opened or acted on by the person. A successful provider API response does not prove that a phone displayed a push or that an email was read. The product should specify which of these promises matters for each event.',
      'This design supports push, email, and SMS. A signed-in client registers device tokens; account settings store verified addresses and phone numbers. Transactional and promotional traffic have distinct policies. User consent and channel eligibility are part of the send decision, not a cleanup step after delivery.',
    ],
    takeaways: ['Define delivery states separately; provider acceptance is not human receipt.', 'Classify urgency, consent, channels, and peak volume before selecting infrastructure.'],
    diagramId: 'notification-scope',
    scenario: 'A product manager says “send every user a notification instantly” after a sale begins. What must be clarified first?',
    scenarioAnswer: 'Ask which users consented, which channels are allowed, whether this is promotional, the expected burst size, the acceptable delay, and whether success means accepted by the provider or observed engagement. A sale alert can usually be paced or batched rather than promised instant delivery.',
  },
  {
    id: 'notification-ingest', title: 'Accept an event without losing it', eyebrow: '02 · Event entry',
    summary: 'Authenticate producers, validate the request, persist intent, and queue work.',
    body: [
      'A trusted product service submits a notification intent with event ID, recipient, category, template version, parameters, and requested send time. The notification API authenticates that producer, checks schema and authorization, and assigns a stable notification ID. A public unauthenticated send endpoint would invite spam and costly provider calls.',
      'Persist the intent before acknowledging acceptance. An outbox record committed with a product transaction is useful when the product change and its notification must move together. A dispatcher then publishes the intent to durable work queues. If publishing fails, it retries from the outbox; acknowledging a request before both intent and recovery path exist risks silent loss.',
      'Queues buffer bursts and let workers scale independently. Split work by channel or priority so an SMS provider outage does not block email, and reserve capacity for urgent transactional events. A queue still needs retention, monitoring, and backpressure; it is not itself proof of delivery.',
    ],
    takeaways: ['Acknowledge only after the send intent has a durable recovery path.', 'Separate channel and priority workloads so one slow provider does not stall every notification.'],
    diagramId: 'notification-ingest',
    scenario: 'An order commits, but the process crashes before it publishes the receipt event. How can the system avoid losing the receipt?',
    scenarioAnswer: 'Commit an outbox record with the order, then have a separate publisher retry the record until the notification service durably accepts it. Use a stable event ID so publishing the same record again does not create a second logical intent.',
  },
  {
    id: 'notification-personalize', title: 'Resolve who should receive what', eyebrow: '03 · Policy and content',
    summary: 'Read current contact, consent, and template data before fanout.',
    body: [
      'A recipient may have two current push tokens, an email address, and no verified phone number. Store device tokens by device, remove tokens rejected as invalid, and verify email or phone ownership before using those channels. A user-level destination alone cannot describe multi-device push.',
      'Evaluate notification category and channel preferences before creating delivery attempts. Promotional opt-out and quiet-hour rules should be explicit; legal or essential transactional exceptions require a product policy, not an accidental bypass. Recheck mutable consent close to send time, especially for scheduled work. Record the policy and template version used so operators can explain a historical delivery.',
      'Render a versioned template with validated data and channel-specific limits. Escape untrusted fields, avoid putting secrets in lock-screen push payloads, and use localization where required. A deduplication key such as event ID plus recipient plus category prevents repeat intents from generating another campaign message; it should not collapse distinct legitimate events.',
    ],
    takeaways: ['Eligibility depends on current consent, verified destinations, and device state.', 'Version templates and define the exact scope of deduplication.'],
    diagramId: 'notification-personalize',
    scenario: 'A user opts out of marketing email after a campaign was queued but before its scheduled send. What should happen?',
    scenarioAnswer: 'The send worker rechecks current marketing-email consent and suppresses the attempt. Record the suppression reason for support and analytics; an earlier eligibility check does not override a later opt-out.',
  },
  {
    id: 'notification-channels', title: 'Hand off through channel workers', eyebrow: '04 · Delivery paths',
    summary: 'Adapt the same intent to push, email, and SMS providers without coupling their failures.',
    body: [
      'A channel worker pulls eligible attempts from its queue and calls a provider adapter. Push uses a device token and a platform push service; email uses an email provider; SMS uses an SMS gateway. Provider adapters isolate request formats, credentials, rate rules, and response codes so a replacement provider does not change event ingestion.',
      'The worker records a provider request ID and outcome. A provider acknowledgement means it accepted the request, not that the recipient saw it. Device-token invalidation, email bounces, SMS delivery receipts, and open events are separate later signals with varying reliability. Treat provider callbacks as untrusted input: authenticate them and deduplicate repeated status events.',
      'A fallback channel is a product decision. An email outage should not automatically turn every promotional email into an expensive SMS or bypass consent. If a critical alert permits fallback, define a delay, allowed channels, and a shared notification ID so two successes do not surprise the user.',
    ],
    takeaways: ['Channel adapters contain provider-specific behavior while queues isolate outages.', 'Provider acceptance, downstream delivery, and user engagement are different observations.'],
    diagramId: 'notification-channels',
    scenario: 'The push provider accepts an alert, but the user’s device is offline. Should the system mark it as read or immediately send SMS?',
    scenarioAnswer: 'Neither. Mark provider acceptance, wait for any later device or app signal, and follow the alert’s explicit fallback policy if one exists. Offline push can be delayed; SMS needs its own consent and cost rule.',
  },
  {
    id: 'notification-reliability', title: 'Recover from ambiguous failure', eyebrow: '05 · Retries and idempotency',
    summary: 'Plan for repeated work and uncertain provider responses.',
    body: [
      'Workers commonly provide at-least-once processing. If one crashes after a provider accepts a request but before the worker stores the result, the queue may deliver the attempt again. Use a stable delivery-attempt key, a uniqueness constraint on logical intent, and a provider idempotency key where supported. These reduce duplicates, but an external provider that lacks idempotency can leave an unavoidable ambiguity.',
      'Classify failures before retrying. A timeout or provider 5xx may be transient; use exponential backoff with jitter, a retry limit, and circuit breaking when the provider is broadly unhealthy. Invalid tokens, malformed addresses, and denied consent are permanent outcomes and should not be retried. After the bounded retry budget, move the attempt to a dead-letter queue with context for inspection and controlled replay.',
      'Persist attempt state and audit transitions so a crash cannot erase the work. When replaying a dead-letter item, retain its original notification identity. Do not claim exactly-once delivery across independent services; state the actual guarantee and the residual duplicate risk.',
    ],
    takeaways: ['At-least-once work requires idempotency and explicit duplicate handling.', 'Retry transient failures; quarantine permanent or exhausted attempts with a replay path.'],
    diagramId: 'notification-reliability',
    scenario: 'A worker times out after sending an SMS; the provider may have accepted it. What is the safest next step?',
    scenarioAnswer: 'Check the provider using the request or idempotency key if its API supports that. Otherwise mark the attempt ambiguous and follow a policy that weighs duplicate SMS cost against missed delivery; blindly retrying cannot guarantee exactly one message.',
  },
  {
    id: 'notification-pacing', title: 'Control when and how much to send', eyebrow: '06 · Scheduling and load',
    summary: 'Respect send times, quiet hours, user frequency caps, and provider capacity.',
    body: [
      'A scheduled campaign stores a due time and recipient selection plan. A scheduler releases due intents into channel queues in bounded batches, taking account of time zones, quiet hours, and newly changed preferences. For a large audience, avoid loading every recipient into one process or firing the whole campaign in one second.',
      'Apply limits at several levels: an individual user should not receive too many promotional messages; each provider account has a throughput or cost budget; urgent transactional work may need reserved capacity. These limits solve different problems. A global provider quota does not prevent one user from being overwhelmed, and a per-user cap does not protect a provider during a huge burst.',
      'Batching reduces provider calls when the channel supports it, but batches should remain small enough for retries and per-recipient status. Queue age, not only queue length, reveals whether a campaign is making people wait beyond its promised window. Drop stale promotional items only under a documented expiry policy; do not silently drop transactional alerts.',
    ],
    takeaways: ['Schedule and pace large fanouts rather than releasing all recipients at once.', 'Use separate user-frequency and provider-capacity limits.'],
    diagramId: 'notification-pacing',
    scenario: 'A campaign for five million users is due at 9 a.m. local time, while receipts must still arrive quickly. How should the scheduler release work?',
    scenarioAnswer: 'Partition by local time and recipient, release bounded batches under provider quotas, enforce consent and per-user frequency caps near send time, and keep reserved queue capacity for receipts. Watch oldest-item age to catch delays.',
  },
  {
    id: 'notification-operations', title: 'Measure the full delivery path', eyebrow: '07 · Operations',
    summary: 'Trace an intent through queues, providers, callbacks, and user action.',
    body: [
      'Track accepted intents, eligibility suppressions, queue age, worker failures, provider latency and error rate, retries, dead-letter count, accepted-by-provider rate, bounces, and invalid tokens. Label these by channel, provider, and priority without placing personal content in metrics or logs. Alert on end-to-end time for urgent messages, not just total queue depth.',
      'An event timeline keyed by notification ID lets support answer what happened: accepted, suppressed, queued, attempted, accepted by provider, bounced, or opened where measurable. Open and click events are incomplete and affected by client behavior; they are product signals, not a delivery proof. Retain only necessary personal data and constrain access to message content.',
      'For provider outages, pause or divert the affected queue according to policy, keep the durable backlog, use controlled retries or a consented fallback, and monitor age against the promise. Drill a failure where one provider is down while others continue, and another where a callback is duplicated. The design is complete only when operators can explain and recover those paths.',
    ],
    takeaways: ['Follow one stable ID through acceptance, policy, queue, provider, and callback states.', 'Measure age and user-facing delay; queue depth alone can hide slow delivery.'],
    diagramId: 'notification-operations',
    scenario: 'Email queue depth is steady, but some receipts arrive two hours late. What should an operator inspect?',
    scenarioAnswer: 'Check oldest-item age and end-to-end latency by priority, worker throughput, provider throttling and errors, retry churn, and whether campaign traffic consumed receipt capacity. Stable depth does not mean a timely queue.',
  },
];

export const notificationQuestions: Question[] = [
  { id:'notification-q01', stepId:'notification-scope', difficulty:'Recall', prompt:'What does a successful response from an email provider prove?', options:['The person read the email','The provider accepted the request','The inbox displayed it','The message was clicked'], correctIndex:1, explanation:'Provider acceptance is only one state. Later delivery, display, and engagement require separate evidence.' },
  { id:'notification-q02', stepId:'notification-scope', difficulty:'Apply', prompt:'A weekly digest is delayed 15 minutes during a traffic spike. Which requirement decides whether that is acceptable?', options:['The number of templates','The push token format','The documented timeliness target for the digest','The worker language'], correctIndex:2, explanation:'Urgency and latency targets differ by notification category; a digest can usually tolerate delay.' },
  { id:'notification-q03', stepId:'notification-scope', difficulty:'Diagnose', prompt:'A dashboard counts provider acceptance as “user notified.” What is misleading?', options:['Provider acceptance is not proof of device display or human receipt','The dashboard needs more colors','SMS requires no provider','Only push can be sent asynchronously'], correctIndex:0, explanation:'The label promises more than the system observed.' },
  { id:'notification-q04', stepId:'notification-ingest', difficulty:'Recall', prompt:'Why persist a send intent before acknowledging it?', options:['To improve icon rendering','To avoid authentication','To remove the need for queues','To retain a recovery path after process failure'], correctIndex:3, explanation:'An acknowledged request must survive a crash and be publishable or retryable later.' },
  { id:'notification-q05', stepId:'notification-ingest', difficulty:'Apply', prompt:'An order and its receipt event must be committed together. Which pattern addresses the crash between them?', options:['A larger HTTP timeout','A transactional outbox','A CDN cache','A browser cookie'], correctIndex:1, explanation:'The order and outbox row commit atomically; a dispatcher can later retry publication.' },
  { id:'notification-q06', stepId:'notification-ingest', difficulty:'Diagnose', prompt:'An SMS provider outage also stops all email processing. What design boundary is missing?', options:['A shorter template','A second DNS server','Channel-isolated work queues and workers','A higher display resolution'], correctIndex:2, explanation:'Separate queues and workers prevent one provider’s backlog from consuming every channel’s capacity.' },
  { id:'notification-q07', stepId:'notification-personalize', difficulty:'Recall', prompt:'Why store push tokens per device?', options:['One account may have multiple active devices','Tokens replace user consent','It makes email unnecessary','Every device shares one permanent token'], correctIndex:0, explanation:'Push destinations belong to devices and may change or become invalid independently.' },
  { id:'notification-q08', stepId:'notification-personalize', difficulty:'Apply', prompt:'A queued promotional email is due after the user opts out. What should the send worker do?', options:['Send because it was queued earlier','Send by SMS instead','Ignore the current setting','Recheck consent and suppress the email'], correctIndex:3, explanation:'Mutable preferences must be checked close to send time, especially for scheduled delivery.' },
  { id:'notification-q09', stepId:'notification-personalize', difficulty:'Diagnose', prompt:'Two different purchase receipts are collapsed into one by deduplication. What likely went wrong?', options:['The template used localization','The deduplication key was too broad','The email address was verified','The queue has too many partitions'], correctIndex:1, explanation:'Deduplication must identify one logical event and recipient, not every event in a category.' },
  { id:'notification-q10', stepId:'notification-channels', difficulty:'Recall', prompt:'What does a provider adapter isolate?', options:['The user’s browser history','The product’s payment database','Provider request formats, credentials, and response handling','All retry decisions from operations'], correctIndex:2, explanation:'Adapters contain provider-specific integration details while the intent and queue model remain stable.' },
  { id:'notification-q11', stepId:'notification-channels', difficulty:'Apply', prompt:'When should a push failure trigger an SMS fallback?', options:['Only when a defined alert policy allows SMS and the user is eligible','Always after one timeout','Whenever the user is offline','For every promotional message'], correctIndex:0, explanation:'Fallback changes cost and channel consent and must be an explicit product rule.' },
  { id:'notification-q12', stepId:'notification-channels', difficulty:'Diagnose', prompt:'A provider callback reports the same bounce twice. How should the system handle it?', options:['Create two new intents','Treat each callback as a separate user','Mark the address verified','Authenticate and deduplicate the repeated status event'], correctIndex:3, explanation:'Callbacks can repeat and should update the same attempt state idempotently.' },
  { id:'notification-q13', stepId:'notification-reliability', difficulty:'Recall', prompt:'What delivery behavior should a queue worker normally assume?', options:['Exactly one execution','At-least-once execution with possible retries','No process crashes','Provider calls are reversible'], correctIndex:1, explanation:'A crash before acknowledgement can cause work to be delivered to a worker again.' },
  { id:'notification-q14', stepId:'notification-reliability', difficulty:'Apply', prompt:'The provider returns “invalid device token.” What should happen?', options:['Retry forever','Switch to SMS automatically','Mark the token invalid and stop retrying that attempt','Increase queue retention'], correctIndex:2, explanation:'An invalid token is a permanent failure; retrying it wastes capacity.' },
  { id:'notification-q15', stepId:'notification-reliability', difficulty:'Diagnose', prompt:'A worker times out after sending to a provider that offers no idempotency key or lookup. What remains uncertain?', options:['Whether the provider accepted the first attempt','The user’s country','The original template version','The queue name'], correctIndex:0, explanation:'A timeout may follow successful acceptance. A blind retry can duplicate delivery.' },
  { id:'notification-q16', stepId:'notification-pacing', difficulty:'Recall', prompt:'Why are a per-user cap and provider throughput limit both useful?', options:['Both are identical counters','One stores templates and one stores tokens','They only apply to SMS','One protects recipients; the other protects provider capacity and cost'], correctIndex:3, explanation:'The two limits address distinct constraints and should be enforced independently.' },
  { id:'notification-q17', stepId:'notification-pacing', difficulty:'Apply', prompt:'A large campaign and urgent receipts share a send pipeline. What helps preserve receipt latency?', options:['Delete every campaign item','Reserve priority capacity and release the campaign in bounded batches','Make receipts promotional','Use one unbounded batch'], correctIndex:1, explanation:'Pacing campaign work and reserving transactional capacity prevent a bulk release from starving receipts.' },
  { id:'notification-q18', stepId:'notification-pacing', difficulty:'Diagnose', prompt:'Queue length stays at 10,000 while the oldest message gets older. What does that reveal?', options:['The queue is definitely healthy','Every message was read','Arrival and processing may balance while individual work misses its latency target','The provider has infinite throughput'], correctIndex:2, explanation:'Stable depth can conceal aging work, retries, or priority starvation.' },
  { id:'notification-q19', stepId:'notification-operations', difficulty:'Recall', prompt:'Which identifier should connect ingestion, attempts, provider responses, and callbacks?', options:['A stable notification ID','A browser session ID','The current worker PID','The CSS class name'], correctIndex:0, explanation:'A stable ID makes an end-to-end audit timeline and deduplication possible.' },
  { id:'notification-q20', stepId:'notification-operations', difficulty:'Apply', prompt:'An email provider is down while SMS remains healthy. What is a sound response?', options:['Discard the email backlog','Pause all channels','Send all email intents by SMS','Retain and control the email backlog while other channels continue'], correctIndex:3, explanation:'Channel isolation and durable queues let healthy providers continue while email is retried or held under policy.' },
  { id:'notification-q21', stepId:'notification-operations', difficulty:'Diagnose', prompt:'Open rate drops suddenly, but provider acceptance and bounces are unchanged. What should be concluded?', options:['Every email was lost','Investigate tracking changes and client behavior before treating opens as delivery proof','The worker queue is empty','The send API must be public'], correctIndex:1, explanation:'Open events are incomplete product signals. Their collection can change independently of provider acceptance or actual delivery.' },
];
