import type { Question, Step } from './chapter';

export const urlSteps: Step[] = [
  {
    id: 'url-scope',
    title: 'Define the promise and estimate demand',
    eyebrow: '01 · Scope and scale',
    summary: 'A tiny link hides a read-heavy system with a durable mapping.',
    body: [
      'A shortener has two core actions: accept a long URL and return a short link, then resolve that link to the original destination. Agree on allowed schemes, link lifetime, whether a destination can change, custom aliases, and whether click analytics matters. These choices affect storage, redirects, and abuse controls.',
      'Suppose the service creates 100 million links each day and each is opened ten times. Average creation traffic is about 1,160 writes per second; redirects average about 11,600 reads per second. Peaks need separate headroom. Ten years yields about 365 billion mappings. At 100 bytes of destination text each, that is about 36.5 TB of raw URL text, before identifiers, indexes, metadata, replicas, and overhead.',
    ],
    takeaways: ['Define the link contract before choosing a key algorithm.', 'Keep units, time horizon, peak factor, and storage overhead visible.'],
    diagramId: 'url-scope',
    scenario: 'A team says “make links as short as possible” but also wants ten years of retention. What do you clarify first?',
    scenarioAnswer: 'Clarify the expected number of mappings, allowed alphabet, whether links expire or change, and whether aliases are user-selected. These set the key-space and storage requirements; “short” alone cannot determine a safe length.',
  },
  {
    id: 'url-contract',
    title: 'Design creation and lookup together',
    eyebrow: '02 · API and data model',
    summary: 'The creation response must leave a durable mapping for every later redirect.',
    body: [
      'A client can POST a destination URL to create a link. The service validates it, assigns a unique key, persists a record, then returns the complete short URL. A request to GET /{key} looks up that record and responds with an HTTP Location header. Store the key, destination, creation time, and optional expiry; enforce a unique index on the key.',
      'Choose an explicit duplicate policy. Reusing a key for the same destination can reduce storage, but distinct owners, expiry dates, and analytics often require distinct records. For retry safety, a caller-provided idempotency key can return the same creation result after a network timeout without forcing global destination deduplication.',
    ],
    takeaways: ['Persist before acknowledging creation so a returned link resolves.', 'A unique key index and an explicit duplicate policy protect the mapping contract.'],
    diagramId: 'url-contract',
    scenario: 'The client times out after POST and retries. Should the server always create a second link?',
    scenarioAnswer: 'No. If the API supports an idempotency key, the retry should return the first result. If it does not, duplicate links may be acceptable under an explicit product policy, but the service should not silently assume that equal destinations mean equal owners or expiry.',
  },
  {
    id: 'url-redirect',
    title: 'Choose redirect and expiry semantics',
    eyebrow: '03 · Read behavior',
    summary: 'HTTP status codes determine who sees future clicks and how failures appear.',
    body: [
      'For a valid key, respond with a redirect and a Location header pointing to the saved destination. A 301 expresses a permanent move and can be reused by browsers or intermediaries, reducing service traffic. A 302 expresses a temporary move and is usually preferable when the service should observe later clicks or the destination may change. Cache headers and client behavior still matter; neither status alone guarantees an exact analytics count.',
      'Check expiry before redirecting. An unknown key can return 404; a known, deliberately expired link may return 410. Never redirect an expired link to an old destination. If deletion or editing is out of scope, say so; otherwise define how caches and browser-stored redirects are invalidated or allowed to age out.',
    ],
    takeaways: ['301 and 302 are product and caching decisions, not just performance switches.', 'TTL and error responses are part of the public link contract.'],
    diagramId: 'url-redirect',
    scenario: 'The product needs accurate per-click reporting and destinations can change. Which redirect is safer?',
    scenarioAnswer: 'Use a temporary redirect such as 302, with cache headers chosen for the reporting and update requirements. A permanent redirect can let a browser bypass the service on later visits, so those visits may never reach your analytics pipeline.',
  },
  {
    id: 'url-keys',
    title: 'Generate keys without collisions',
    eyebrow: '04 · Identity and tradeoffs',
    summary: 'The key-space must fit demand, and concurrent creation must preserve uniqueness.',
    body: [
      'Base62 uses digits and uppercase and lowercase letters. Six characters provide about 56.8 billion combinations; seven provide about 3.52 trillion, enough for the example’s 365 billion mappings before reservations and uneven allocation. A unique integer encoded in base62 is compact and collision-free when the ID allocator is truly unique. It also exposes a guessable sequence unless keys are obfuscated or access policy accepts enumeration.',
      'A random key hides ordering but needs collision detection. Generate a candidate, insert with a unique constraint, and retry on conflict. Truncating a hash of the destination also creates collision risk and couples identity to URL normalization; merely checking for an existing key before insertion is not safe under concurrent writers. Custom aliases need the same atomic uniqueness guarantee.',
    ],
    takeaways: ['Estimate key-space from lifetime creations, not daily traffic alone.', 'Let an atomic unique constraint decide collisions under concurrency.'],
    diagramId: 'url-keys',
    scenario: 'Two creation servers generate the same random key at once. Both check that it is unused. What prevents duplicate ownership?',
    scenarioAnswer: 'A database unique constraint or equivalent atomic reservation allows only one insertion. The losing server generates another candidate and retries. A separate read-before-write check cannot close the race.',
  },
  {
    id: 'url-scale',
    title: 'Make the read path cheap',
    eyebrow: '05 · Cache and capacity',
    summary: 'Most traffic resolves existing keys, so optimize lookup without making cache the source of truth.',
    body: [
      'Place stateless redirect servers behind a load balancer. On a cache hit they read the key-to-destination mapping and return the redirect. On a miss they query persistent storage, fill the cache, and respond. A missing key should not be cached forever because a future creation or recovery may change the answer.',
      'Popular links create skew: a small set may receive most reads. Measure cache hit rate, database lookup latency, and redirect traffic before adding replicas or partitioning by key. Replicas can expand reads but may lag a new write; a just-created link should resolve reliably through the chosen consistency path. Sharding becomes useful when storage or write demand exceeds one database tier, not merely because traffic sounds large.',
    ],
    takeaways: ['Cache mappings for read speed while the database remains durable authority.', 'Treat the first redirect after creation as a consistency requirement.'],
    diagramId: 'url-scale',
    scenario: 'A newly created link returns 404 for a few seconds while reads use lagging replicas. What should change?',
    scenarioAnswer: 'Route recent-key lookups to a strongly consistent source or populate the cache after the durable write. Check negative-cache TTLs as well. Adding more replicas without addressing lag may make the symptom worse.',
  },
  {
    id: 'url-operations',
    title: 'Plan for failure and misuse',
    eyebrow: '06 · Operate and protect',
    summary: 'A redirect service must remain trustworthy when dependencies fail or attackers create links.',
    body: [
      'If a cache node fails, redirect servers fall back to the database, so protect it with capacity and controlled retry behavior. If durable storage is unavailable, existing hot keys may still redirect from cache for a limited time, but creation should not claim success until its mapping is durable. Monitor error rate, redirect latency, cache hit rate, database pressure, and key-generation conflicts.',
      'Validate destination schemes such as http and https and reject unsafe schemes. Rate-limit creation, and have a policy for spam, phishing, and malicious destinations. Do not fetch submitted URLs from privileged infrastructure without SSRF defenses. If click analytics is needed, publish an event asynchronously; a failed analytics sink should not usually hold up the redirect.',
    ],
    takeaways: ['Separate durability of new links from availability of cached redirects.', 'Abuse controls and observability are part of the service, not optional polish.'],
    diagramId: 'url-operations',
    scenario: 'An analytics queue is unavailable while people click existing links. Should redirects wait for it?',
    scenarioAnswer: 'Usually no. Return the redirect from the mapping path and buffer or drop analytics according to a documented reliability target. Alert on event loss and queue health, but avoid turning a reporting dependency into a redirect outage.',
  },
];

export const urlQuestions: Question[] = [
  { id: 'uq01', stepId: 'url-scope', difficulty: 'Apply', prompt: 'At 100 million new links per day, roughly how many creation requests arrive per second on average?', options: ['About 12', 'About 1,160', 'About 11,600', 'About 100 million'], correctIndex: 1, explanation: 'Divide 100,000,000 by 86,400 seconds per day. The result is about 1,157 writes per second before peak headroom.' },
  { id: 'uq02', stepId: 'url-scope', difficulty: 'Diagnose', prompt: 'Why is 36.5 TB an incomplete ten-year storage estimate for 365 billion links with 100-byte destinations?', options: ['It assumes every link is read once', 'It includes too many replicas', 'It ignores identifiers, indexes, metadata, and copies', 'It counts URL text twice'], correctIndex: 2, explanation: '365 billion times 100 bytes is 36.5 TB of raw destination text. A real record also has a key and metadata, and databases add indexes, storage overhead, and often replicas.' },
  { id: 'uq03', stepId: 'url-scope', difficulty: 'Recall', prompt: 'Which decision should be settled before choosing a minimum key length?', options: ['Lifetime number of links and allowed characters', 'The button color', 'The cache vendor', 'The DNS TTL alone'], correctIndex: 0, explanation: 'Key-space depends on the alphabet and total number of distinct keys needed over the service lifetime, including growth and reserved values.' },
  { id: 'uq04', stepId: 'url-contract', difficulty: 'Apply', prompt: 'What must happen before a creation API acknowledges a new short link?', options: ['The first redirect must occur', 'Click analytics must be aggregated', 'The link must be posted to social media', 'The mapping must be durably stored'], correctIndex: 3, explanation: 'A returned link promises future resolution. Persist its mapping before claiming creation succeeded.' },
  { id: 'uq05', stepId: 'url-contract', difficulty: 'Diagnose', prompt: 'A POST succeeds, but its response is lost and the client retries. What API feature can return the original result?', options: ['A shorter DNS TTL', 'A caller-provided idempotency key', 'A 301 redirect', 'A CDN purge'], correctIndex: 1, explanation: 'An idempotency key identifies the logical creation attempt, so a retry can retrieve the same result without requiring all users of one destination to share a link.' },
  { id: 'uq06', stepId: 'url-contract', difficulty: 'Recall', prompt: 'Which field needs an atomic uniqueness guarantee in the mapping table?', options: ['Destination scheme', 'Created-at timestamp', 'Short key', 'Click count'], correctIndex: 2, explanation: 'Every key must identify at most one destination. A unique constraint or atomic reservation enforces that even during concurrent creation.' },
  { id: 'uq07', stepId: 'url-redirect', difficulty: 'Apply', prompt: 'Why might a service prefer a 302 over a 301 for links whose destinations can change?', options: ['It reduces every database read to zero', 'It guarantees exactly one analytics event per click', 'It prevents all browser caching', 'It communicates a temporary destination and reduces permanent client reuse'], correctIndex: 3, explanation: 'A 301 can be retained by clients and bypass later service requests. A 302 better represents a changeable destination, though actual caching depends on headers and client behavior.' },
  { id: 'uq08', stepId: 'url-redirect', difficulty: 'Diagnose', prompt: 'A known link has passed its declared expiry. What is the best behavior?', options: ['Return a non-redirect response such as 410', 'Continue redirecting until its cache entry expires', 'Redirect to a random active link', 'Issue a 301 to the old destination'], correctIndex: 0, explanation: 'Expiry is part of the public contract. A known expired resource may return 410; serving a stale redirect breaks the promised lifetime.' },
  { id: 'uq09', stepId: 'url-redirect', difficulty: 'Recall', prompt: 'Which HTTP response header carries the destination for a redirect?', options: ['Content-Length', 'Location', 'ETag', 'Accept'], correctIndex: 1, explanation: 'The Location header tells the client where to navigate after receiving the redirect status.' },
  { id: 'uq10', stepId: 'url-keys', difficulty: 'Apply', prompt: 'Why can seven base62 characters cover 365 billion lifetime mappings while six cannot?', options: ['Seven characters disable collisions', 'The alphabet has seven symbols', '62^6 is about 56.8 billion; 62^7 is about 3.52 trillion', 'Seven characters guarantee unguessability'], correctIndex: 2, explanation: 'The key-space grows by a factor of 62 per character. Six positions are too small for 365 billion unique mappings, while seven have room in this simplified example.' },
  { id: 'uq11', stepId: 'url-keys', difficulty: 'Diagnose', prompt: 'Two servers both see that a generated key is unused. What closes the race?', options: ['A database unique constraint and retry on conflict', 'A longer sleep between checks', 'A browser cache', 'A 302 redirect'], correctIndex: 0, explanation: 'The check and reservation must be atomic. A unique index rejects one concurrent insert; that server generates another key and retries.' },
  { id: 'uq12', stepId: 'url-keys', difficulty: 'Apply', prompt: 'What tradeoff comes with base62-encoding sequential IDs?', options: ['It cannot be decoded', 'It requires URL normalization', 'It always collides', 'Adjacent links may be enumerable'], correctIndex: 3, explanation: 'Unique sequential IDs avoid key collisions, but their base62 representation can reveal order and make nearby links easy to guess. Use another scheme or policy if that matters.' },
  { id: 'uq13', stepId: 'url-scale', difficulty: 'Recall', prompt: 'On a redirect cache miss, where should the service obtain the authoritative destination?', options: ['A browser cookie', 'Persistent mapping storage', 'The analytics queue', 'A CDN image cache'], correctIndex: 1, explanation: 'The cache is a speed layer. The stored key-to-destination mapping is the durable authority and supplies cache misses.' },
  { id: 'uq14', stepId: 'url-scale', difficulty: 'Diagnose', prompt: 'A brand-new key returns 404 from a lagging read replica. Which fix targets the cause?', options: ['Add more read replicas only', 'Turn every redirect into a 301', 'Use a consistent read path or fill cache after the durable write', 'Remove the unique key index'], correctIndex: 2, explanation: 'The issue is visibility after creation. A consistent source for recent keys or a safely populated cache can satisfy the first-read guarantee.' },
  { id: 'uq15', stepId: 'url-scale', difficulty: 'Apply', prompt: 'Which signal best shows whether redirect caching is relieving the database?', options: ['Number of UI pages', 'Length of the domain name', 'Count of creation retries alone', 'Cache hit rate together with database lookup load'], correctIndex: 3, explanation: 'A high cache hit rate should reduce database lookups. Observe both, plus latency, because one metric alone can hide misses or skew.' },
  { id: 'uq16', stepId: 'url-operations', difficulty: 'Diagnose', prompt: 'Persistent storage is unavailable. Which action must not claim success?', options: ['Creating a new link without a durable mapping', 'Serving a cached valid redirect within policy', 'Reporting a storage alert', 'Measuring cache hit rate'], correctIndex: 0, explanation: 'A new link is unusable if its mapping can be lost. Cached existing redirects may continue temporarily, but creation needs durable persistence.' },
  { id: 'uq17', stepId: 'url-operations', difficulty: 'Apply', prompt: 'What should happen if an optional click-event pipeline is temporarily down?', options: ['Block every redirect indefinitely', 'Serve the redirect and handle analytics loss or buffering by policy', 'Delete the short link', 'Turn the destination into a 301 automatically'], correctIndex: 1, explanation: 'The redirect is the core user action. Analytics should normally be asynchronous, with an explicit buffering, retry, or loss policy and monitoring.' },
  { id: 'uq18', stepId: 'url-operations', difficulty: 'Recall', prompt: 'Which creation-time protection addresses both malformed destinations and abusive traffic?', options: ['Use only a CDN', 'Make the key longer', 'Validate allowed URL schemes and rate-limit creation', 'Disable logging'], correctIndex: 2, explanation: 'Scheme validation rejects unsafe destinations, while rate limits constrain mass creation. Separate policies still need to address malicious but syntactically valid destinations.' },
];
